// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ADCTrajectory.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_ADCTRAJECTORY_H_
#define _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_ADCTRAJECTORY_H_

#include "TrajectoryPoint.h"
#include "Header.h"
#include "EStop.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ADCTRAJECTORY_SOURCE)
#define ADCTRAJECTORY_DllAPI __declspec( dllexport )
#else
#define ADCTRAJECTORY_DllAPI __declspec( dllimport )
#endif // ADCTRAJECTORY_SOURCE
#else
#define ADCTRAJECTORY_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ADCTRAJECTORY_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace ros2_interface {
    namespace msg {
        /*!
         * @brief This class represents the structure ADCTrajectory defined by the user in the IDL file.
         * @ingroup ADCTrajectory
         */
        class ADCTrajectory
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport ADCTrajectory();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~ADCTrajectory();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object ros2_interface::msg::ADCTrajectory that will be copied.
             */
            eProsima_user_DllExport ADCTrajectory(
                    const ADCTrajectory& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object ros2_interface::msg::ADCTrajectory that will be copied.
             */
            eProsima_user_DllExport ADCTrajectory(
                    ADCTrajectory&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object ros2_interface::msg::ADCTrajectory that will be copied.
             */
            eProsima_user_DllExport ADCTrajectory& operator =(
                    const ADCTrajectory& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object ros2_interface::msg::ADCTrajectory that will be copied.
             */
            eProsima_user_DllExport ADCTrajectory& operator =(
                    ADCTrajectory&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::ADCTrajectory object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const ADCTrajectory& x) const;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::ADCTrajectory object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const ADCTrajectory& x) const;

            /*!
             * @brief This function copies the value in member header
             * @param _header New value to be copied in member header
             */
            eProsima_user_DllExport void header(
                    const ros2_interface::msg::Header& _header);

            /*!
             * @brief This function moves the value in member header
             * @param _header New value to be moved in member header
             */
            eProsima_user_DllExport void header(
                    ros2_interface::msg::Header&& _header);

            /*!
             * @brief This function returns a constant reference to member header
             * @return Constant reference to member header
             */
            eProsima_user_DllExport const ros2_interface::msg::Header& header() const;

            /*!
             * @brief This function returns a reference to member header
             * @return Reference to member header
             */
            eProsima_user_DllExport ros2_interface::msg::Header& header();
            /*!
             * @brief This function sets a value in member total_path_length
             * @param _total_path_length New value for member total_path_length
             */
            eProsima_user_DllExport void total_path_length(
                    double _total_path_length);

            /*!
             * @brief This function returns the value of member total_path_length
             * @return Value of member total_path_length
             */
            eProsima_user_DllExport double total_path_length() const;

            /*!
             * @brief This function returns a reference to member total_path_length
             * @return Reference to member total_path_length
             */
            eProsima_user_DllExport double& total_path_length();

            /*!
             * @brief This function sets a value in member total_path_time
             * @param _total_path_time New value for member total_path_time
             */
            eProsima_user_DllExport void total_path_time(
                    double _total_path_time);

            /*!
             * @brief This function returns the value of member total_path_time
             * @return Value of member total_path_time
             */
            eProsima_user_DllExport double total_path_time() const;

            /*!
             * @brief This function returns a reference to member total_path_time
             * @return Reference to member total_path_time
             */
            eProsima_user_DllExport double& total_path_time();

            /*!
             * @brief This function copies the value in member trajectory_points
             * @param _trajectory_points New value to be copied in member trajectory_points
             */
            eProsima_user_DllExport void trajectory_points(
                    const std::vector<ros2_interface::msg::TrajectoryPoint>& _trajectory_points);

            /*!
             * @brief This function moves the value in member trajectory_points
             * @param _trajectory_points New value to be moved in member trajectory_points
             */
            eProsima_user_DllExport void trajectory_points(
                    std::vector<ros2_interface::msg::TrajectoryPoint>&& _trajectory_points);

            /*!
             * @brief This function returns a constant reference to member trajectory_points
             * @return Constant reference to member trajectory_points
             */
            eProsima_user_DllExport const std::vector<ros2_interface::msg::TrajectoryPoint>& trajectory_points() const;

            /*!
             * @brief This function returns a reference to member trajectory_points
             * @return Reference to member trajectory_points
             */
            eProsima_user_DllExport std::vector<ros2_interface::msg::TrajectoryPoint>& trajectory_points();
            /*!
             * @brief This function sets a value in member car_action
             * @param _car_action New value for member car_action
             */
            eProsima_user_DllExport void car_action(
                    int32_t _car_action);

            /*!
             * @brief This function returns the value of member car_action
             * @return Value of member car_action
             */
            eProsima_user_DllExport int32_t car_action() const;

            /*!
             * @brief This function returns a reference to member car_action
             * @return Reference to member car_action
             */
            eProsima_user_DllExport int32_t& car_action();

            /*!
             * @brief This function sets a value in member behaviour_state
             * @param _behaviour_state New value for member behaviour_state
             */
            eProsima_user_DllExport void behaviour_state(
                    int32_t _behaviour_state);

            /*!
             * @brief This function returns the value of member behaviour_state
             * @return Value of member behaviour_state
             */
            eProsima_user_DllExport int32_t behaviour_state() const;

            /*!
             * @brief This function returns a reference to member behaviour_state
             * @return Reference to member behaviour_state
             */
            eProsima_user_DllExport int32_t& behaviour_state();

            /*!
             * @brief This function sets a value in member behaviour_lon_state
             * @param _behaviour_lon_state New value for member behaviour_lon_state
             */
            eProsima_user_DllExport void behaviour_lon_state(
                    int32_t _behaviour_lon_state);

            /*!
             * @brief This function returns the value of member behaviour_lon_state
             * @return Value of member behaviour_lon_state
             */
            eProsima_user_DllExport int32_t behaviour_lon_state() const;

            /*!
             * @brief This function returns a reference to member behaviour_lon_state
             * @return Reference to member behaviour_lon_state
             */
            eProsima_user_DllExport int32_t& behaviour_lon_state();

            /*!
             * @brief This function sets a value in member scenario
             * @param _scenario New value for member scenario
             */
            eProsima_user_DllExport void scenario(
                    int32_t _scenario);

            /*!
             * @brief This function returns the value of member scenario
             * @return Value of member scenario
             */
            eProsima_user_DllExport int32_t scenario() const;

            /*!
             * @brief This function returns a reference to member scenario
             * @return Reference to member scenario
             */
            eProsima_user_DllExport int32_t& scenario();

            /*!
             * @brief This function sets a value in member driving_mode
             * @param _driving_mode New value for member driving_mode
             */
            eProsima_user_DllExport void driving_mode(
                    int32_t _driving_mode);

            /*!
             * @brief This function returns the value of member driving_mode
             * @return Value of member driving_mode
             */
            eProsima_user_DllExport int32_t driving_mode() const;

            /*!
             * @brief This function returns a reference to member driving_mode
             * @return Reference to member driving_mode
             */
            eProsima_user_DllExport int32_t& driving_mode();

            /*!
             * @brief This function sets a value in member adc_trajectory_type
             * @param _adc_trajectory_type New value for member adc_trajectory_type
             */
            eProsima_user_DllExport void adc_trajectory_type(
                    int32_t _adc_trajectory_type);

            /*!
             * @brief This function returns the value of member adc_trajectory_type
             * @return Value of member adc_trajectory_type
             */
            eProsima_user_DllExport int32_t adc_trajectory_type() const;

            /*!
             * @brief This function returns a reference to member adc_trajectory_type
             * @return Reference to member adc_trajectory_type
             */
            eProsima_user_DllExport int32_t& adc_trajectory_type();

            /*!
             * @brief This function copies the value in member estop
             * @param _estop New value to be copied in member estop
             */
            eProsima_user_DllExport void estop(
                    const ros2_interface::msg::EStop& _estop);

            /*!
             * @brief This function moves the value in member estop
             * @param _estop New value to be moved in member estop
             */
            eProsima_user_DllExport void estop(
                    ros2_interface::msg::EStop&& _estop);

            /*!
             * @brief This function returns a constant reference to member estop
             * @return Constant reference to member estop
             */
            eProsima_user_DllExport const ros2_interface::msg::EStop& estop() const;

            /*!
             * @brief This function returns a reference to member estop
             * @return Reference to member estop
             */
            eProsima_user_DllExport ros2_interface::msg::EStop& estop();
            /*!
             * @brief This function sets a value in member is_replan
             * @param _is_replan New value for member is_replan
             */
            eProsima_user_DllExport void is_replan(
                    bool _is_replan);

            /*!
             * @brief This function returns the value of member is_replan
             * @return Value of member is_replan
             */
            eProsima_user_DllExport bool is_replan() const;

            /*!
             * @brief This function returns a reference to member is_replan
             * @return Reference to member is_replan
             */
            eProsima_user_DllExport bool& is_replan();

            /*!
             * @brief This function copies the value in member replan_reason
             * @param _replan_reason New value to be copied in member replan_reason
             */
            eProsima_user_DllExport void replan_reason(
                    const std::string& _replan_reason);

            /*!
             * @brief This function moves the value in member replan_reason
             * @param _replan_reason New value to be moved in member replan_reason
             */
            eProsima_user_DllExport void replan_reason(
                    std::string&& _replan_reason);

            /*!
             * @brief This function returns a constant reference to member replan_reason
             * @return Constant reference to member replan_reason
             */
            eProsima_user_DllExport const std::string& replan_reason() const;

            /*!
             * @brief This function returns a reference to member replan_reason
             * @return Reference to member replan_reason
             */
            eProsima_user_DllExport std::string& replan_reason();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const ros2_interface::msg::ADCTrajectory& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            ros2_interface::msg::Header m_header;
            double m_total_path_length;
            double m_total_path_time;
            std::vector<ros2_interface::msg::TrajectoryPoint> m_trajectory_points;
            int32_t m_car_action;
            int32_t m_behaviour_state;
            int32_t m_behaviour_lon_state;
            int32_t m_scenario;
            int32_t m_driving_mode;
            int32_t m_adc_trajectory_type;
            ros2_interface::msg::EStop m_estop;
            bool m_is_replan;
            std::string m_replan_reason;

        };
    } // namespace msg
} // namespace ros2_interface

#endif // _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_ADCTRAJECTORY_H_

