// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ADCTrajectory.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ADCTrajectory.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define ros2_interface_msg_Time_max_cdr_typesize 8ULL;
#define ros2_interface_msg_TrajectoryPoint_max_cdr_typesize 148ULL;
#define ros2_interface_msg_Header_max_cdr_typesize 272ULL;
#define ros2_interface_msg_EStop_max_cdr_typesize 264ULL;
#define ros2_interface_msg_ADCTrajectory_max_cdr_typesize 16044ULL;
#define ros2_interface_msg_PathPoint_max_cdr_typesize 88ULL;
#define ros2_interface_msg_Time_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_TrajectoryPoint_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_Header_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_EStop_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_ADCTrajectory_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_PathPoint_max_key_cdr_typesize 0ULL;

ros2_interface::msg::ADCTrajectory::ADCTrajectory()
{
    // ros2_interface::msg::Header m_header

    // double m_total_path_length
    m_total_path_length = 0.0;
    // double m_total_path_time
    m_total_path_time = 0.0;
    // sequence<ros2_interface::msg::TrajectoryPoint> m_trajectory_points

    // long m_car_action
    m_car_action = 0;
    // long m_behaviour_state
    m_behaviour_state = 0;
    // long m_behaviour_lon_state
    m_behaviour_lon_state = 0;
    // long m_scenario
    m_scenario = 0;
    // long m_driving_mode
    m_driving_mode = 0;
    // long m_adc_trajectory_type
    m_adc_trajectory_type = 0;
    // ros2_interface::msg::EStop m_estop

    // boolean m_is_replan
    m_is_replan = false;
    // string m_replan_reason
    m_replan_reason ="";

}

ros2_interface::msg::ADCTrajectory::~ADCTrajectory()
{













}

ros2_interface::msg::ADCTrajectory::ADCTrajectory(
        const ADCTrajectory& x)
{
    m_header = x.m_header;
    m_total_path_length = x.m_total_path_length;
    m_total_path_time = x.m_total_path_time;
    m_trajectory_points = x.m_trajectory_points;
    m_car_action = x.m_car_action;
    m_behaviour_state = x.m_behaviour_state;
    m_behaviour_lon_state = x.m_behaviour_lon_state;
    m_scenario = x.m_scenario;
    m_driving_mode = x.m_driving_mode;
    m_adc_trajectory_type = x.m_adc_trajectory_type;
    m_estop = x.m_estop;
    m_is_replan = x.m_is_replan;
    m_replan_reason = x.m_replan_reason;
}

ros2_interface::msg::ADCTrajectory::ADCTrajectory(
        ADCTrajectory&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_total_path_length = x.m_total_path_length;
    m_total_path_time = x.m_total_path_time;
    m_trajectory_points = std::move(x.m_trajectory_points);
    m_car_action = x.m_car_action;
    m_behaviour_state = x.m_behaviour_state;
    m_behaviour_lon_state = x.m_behaviour_lon_state;
    m_scenario = x.m_scenario;
    m_driving_mode = x.m_driving_mode;
    m_adc_trajectory_type = x.m_adc_trajectory_type;
    m_estop = std::move(x.m_estop);
    m_is_replan = x.m_is_replan;
    m_replan_reason = std::move(x.m_replan_reason);
}

ros2_interface::msg::ADCTrajectory& ros2_interface::msg::ADCTrajectory::operator =(
        const ADCTrajectory& x)
{

    m_header = x.m_header;
    m_total_path_length = x.m_total_path_length;
    m_total_path_time = x.m_total_path_time;
    m_trajectory_points = x.m_trajectory_points;
    m_car_action = x.m_car_action;
    m_behaviour_state = x.m_behaviour_state;
    m_behaviour_lon_state = x.m_behaviour_lon_state;
    m_scenario = x.m_scenario;
    m_driving_mode = x.m_driving_mode;
    m_adc_trajectory_type = x.m_adc_trajectory_type;
    m_estop = x.m_estop;
    m_is_replan = x.m_is_replan;
    m_replan_reason = x.m_replan_reason;

    return *this;
}

ros2_interface::msg::ADCTrajectory& ros2_interface::msg::ADCTrajectory::operator =(
        ADCTrajectory&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_total_path_length = x.m_total_path_length;
    m_total_path_time = x.m_total_path_time;
    m_trajectory_points = std::move(x.m_trajectory_points);
    m_car_action = x.m_car_action;
    m_behaviour_state = x.m_behaviour_state;
    m_behaviour_lon_state = x.m_behaviour_lon_state;
    m_scenario = x.m_scenario;
    m_driving_mode = x.m_driving_mode;
    m_adc_trajectory_type = x.m_adc_trajectory_type;
    m_estop = std::move(x.m_estop);
    m_is_replan = x.m_is_replan;
    m_replan_reason = std::move(x.m_replan_reason);

    return *this;
}

bool ros2_interface::msg::ADCTrajectory::operator ==(
        const ADCTrajectory& x) const
{

    return (m_header == x.m_header && m_total_path_length == x.m_total_path_length && m_total_path_time == x.m_total_path_time && m_trajectory_points == x.m_trajectory_points && m_car_action == x.m_car_action && m_behaviour_state == x.m_behaviour_state && m_behaviour_lon_state == x.m_behaviour_lon_state && m_scenario == x.m_scenario && m_driving_mode == x.m_driving_mode && m_adc_trajectory_type == x.m_adc_trajectory_type && m_estop == x.m_estop && m_is_replan == x.m_is_replan && m_replan_reason == x.m_replan_reason);
}

bool ros2_interface::msg::ADCTrajectory::operator !=(
        const ADCTrajectory& x) const
{
    return !(*this == x);
}

size_t ros2_interface::msg::ADCTrajectory::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ros2_interface_msg_ADCTrajectory_max_cdr_typesize;
}

size_t ros2_interface::msg::ADCTrajectory::getCdrSerializedSize(
        const ros2_interface::msg::ADCTrajectory& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += ros2_interface::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.trajectory_points().size(); ++a)
    {
        current_alignment += ros2_interface::msg::TrajectoryPoint::getCdrSerializedSize(data.trajectory_points().at(a), current_alignment);}

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += ros2_interface::msg::EStop::getCdrSerializedSize(data.estop(), current_alignment);
    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.replan_reason().size() + 1;


    return current_alignment - initial_alignment;
}

void ros2_interface::msg::ADCTrajectory::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_total_path_length;
    scdr << m_total_path_time;
    scdr << m_trajectory_points;
    scdr << m_car_action;
    scdr << m_behaviour_state;
    scdr << m_behaviour_lon_state;
    scdr << m_scenario;
    scdr << m_driving_mode;
    scdr << m_adc_trajectory_type;
    scdr << m_estop;
    scdr << m_is_replan;
    scdr << m_replan_reason.c_str();

}

void ros2_interface::msg::ADCTrajectory::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_total_path_length;
    dcdr >> m_total_path_time;
    dcdr >> m_trajectory_points;
    dcdr >> m_car_action;
    dcdr >> m_behaviour_state;
    dcdr >> m_behaviour_lon_state;
    dcdr >> m_scenario;
    dcdr >> m_driving_mode;
    dcdr >> m_adc_trajectory_type;
    dcdr >> m_estop;
    dcdr >> m_is_replan;
    dcdr >> m_replan_reason;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void ros2_interface::msg::ADCTrajectory::header(
        const ros2_interface::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void ros2_interface::msg::ADCTrajectory::header(
        ros2_interface::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const ros2_interface::msg::Header& ros2_interface::msg::ADCTrajectory::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
ros2_interface::msg::Header& ros2_interface::msg::ADCTrajectory::header()
{
    return m_header;
}
/*!
 * @brief This function sets a value in member total_path_length
 * @param _total_path_length New value for member total_path_length
 */
void ros2_interface::msg::ADCTrajectory::total_path_length(
        double _total_path_length)
{
    m_total_path_length = _total_path_length;
}

/*!
 * @brief This function returns the value of member total_path_length
 * @return Value of member total_path_length
 */
double ros2_interface::msg::ADCTrajectory::total_path_length() const
{
    return m_total_path_length;
}

/*!
 * @brief This function returns a reference to member total_path_length
 * @return Reference to member total_path_length
 */
double& ros2_interface::msg::ADCTrajectory::total_path_length()
{
    return m_total_path_length;
}

/*!
 * @brief This function sets a value in member total_path_time
 * @param _total_path_time New value for member total_path_time
 */
void ros2_interface::msg::ADCTrajectory::total_path_time(
        double _total_path_time)
{
    m_total_path_time = _total_path_time;
}

/*!
 * @brief This function returns the value of member total_path_time
 * @return Value of member total_path_time
 */
double ros2_interface::msg::ADCTrajectory::total_path_time() const
{
    return m_total_path_time;
}

/*!
 * @brief This function returns a reference to member total_path_time
 * @return Reference to member total_path_time
 */
double& ros2_interface::msg::ADCTrajectory::total_path_time()
{
    return m_total_path_time;
}

/*!
 * @brief This function copies the value in member trajectory_points
 * @param _trajectory_points New value to be copied in member trajectory_points
 */
void ros2_interface::msg::ADCTrajectory::trajectory_points(
        const std::vector<ros2_interface::msg::TrajectoryPoint>& _trajectory_points)
{
    m_trajectory_points = _trajectory_points;
}

/*!
 * @brief This function moves the value in member trajectory_points
 * @param _trajectory_points New value to be moved in member trajectory_points
 */
void ros2_interface::msg::ADCTrajectory::trajectory_points(
        std::vector<ros2_interface::msg::TrajectoryPoint>&& _trajectory_points)
{
    m_trajectory_points = std::move(_trajectory_points);
}

/*!
 * @brief This function returns a constant reference to member trajectory_points
 * @return Constant reference to member trajectory_points
 */
const std::vector<ros2_interface::msg::TrajectoryPoint>& ros2_interface::msg::ADCTrajectory::trajectory_points() const
{
    return m_trajectory_points;
}

/*!
 * @brief This function returns a reference to member trajectory_points
 * @return Reference to member trajectory_points
 */
std::vector<ros2_interface::msg::TrajectoryPoint>& ros2_interface::msg::ADCTrajectory::trajectory_points()
{
    return m_trajectory_points;
}
/*!
 * @brief This function sets a value in member car_action
 * @param _car_action New value for member car_action
 */
void ros2_interface::msg::ADCTrajectory::car_action(
        int32_t _car_action)
{
    m_car_action = _car_action;
}

/*!
 * @brief This function returns the value of member car_action
 * @return Value of member car_action
 */
int32_t ros2_interface::msg::ADCTrajectory::car_action() const
{
    return m_car_action;
}

/*!
 * @brief This function returns a reference to member car_action
 * @return Reference to member car_action
 */
int32_t& ros2_interface::msg::ADCTrajectory::car_action()
{
    return m_car_action;
}

/*!
 * @brief This function sets a value in member behaviour_state
 * @param _behaviour_state New value for member behaviour_state
 */
void ros2_interface::msg::ADCTrajectory::behaviour_state(
        int32_t _behaviour_state)
{
    m_behaviour_state = _behaviour_state;
}

/*!
 * @brief This function returns the value of member behaviour_state
 * @return Value of member behaviour_state
 */
int32_t ros2_interface::msg::ADCTrajectory::behaviour_state() const
{
    return m_behaviour_state;
}

/*!
 * @brief This function returns a reference to member behaviour_state
 * @return Reference to member behaviour_state
 */
int32_t& ros2_interface::msg::ADCTrajectory::behaviour_state()
{
    return m_behaviour_state;
}

/*!
 * @brief This function sets a value in member behaviour_lon_state
 * @param _behaviour_lon_state New value for member behaviour_lon_state
 */
void ros2_interface::msg::ADCTrajectory::behaviour_lon_state(
        int32_t _behaviour_lon_state)
{
    m_behaviour_lon_state = _behaviour_lon_state;
}

/*!
 * @brief This function returns the value of member behaviour_lon_state
 * @return Value of member behaviour_lon_state
 */
int32_t ros2_interface::msg::ADCTrajectory::behaviour_lon_state() const
{
    return m_behaviour_lon_state;
}

/*!
 * @brief This function returns a reference to member behaviour_lon_state
 * @return Reference to member behaviour_lon_state
 */
int32_t& ros2_interface::msg::ADCTrajectory::behaviour_lon_state()
{
    return m_behaviour_lon_state;
}

/*!
 * @brief This function sets a value in member scenario
 * @param _scenario New value for member scenario
 */
void ros2_interface::msg::ADCTrajectory::scenario(
        int32_t _scenario)
{
    m_scenario = _scenario;
}

/*!
 * @brief This function returns the value of member scenario
 * @return Value of member scenario
 */
int32_t ros2_interface::msg::ADCTrajectory::scenario() const
{
    return m_scenario;
}

/*!
 * @brief This function returns a reference to member scenario
 * @return Reference to member scenario
 */
int32_t& ros2_interface::msg::ADCTrajectory::scenario()
{
    return m_scenario;
}

/*!
 * @brief This function sets a value in member driving_mode
 * @param _driving_mode New value for member driving_mode
 */
void ros2_interface::msg::ADCTrajectory::driving_mode(
        int32_t _driving_mode)
{
    m_driving_mode = _driving_mode;
}

/*!
 * @brief This function returns the value of member driving_mode
 * @return Value of member driving_mode
 */
int32_t ros2_interface::msg::ADCTrajectory::driving_mode() const
{
    return m_driving_mode;
}

/*!
 * @brief This function returns a reference to member driving_mode
 * @return Reference to member driving_mode
 */
int32_t& ros2_interface::msg::ADCTrajectory::driving_mode()
{
    return m_driving_mode;
}

/*!
 * @brief This function sets a value in member adc_trajectory_type
 * @param _adc_trajectory_type New value for member adc_trajectory_type
 */
void ros2_interface::msg::ADCTrajectory::adc_trajectory_type(
        int32_t _adc_trajectory_type)
{
    m_adc_trajectory_type = _adc_trajectory_type;
}

/*!
 * @brief This function returns the value of member adc_trajectory_type
 * @return Value of member adc_trajectory_type
 */
int32_t ros2_interface::msg::ADCTrajectory::adc_trajectory_type() const
{
    return m_adc_trajectory_type;
}

/*!
 * @brief This function returns a reference to member adc_trajectory_type
 * @return Reference to member adc_trajectory_type
 */
int32_t& ros2_interface::msg::ADCTrajectory::adc_trajectory_type()
{
    return m_adc_trajectory_type;
}

/*!
 * @brief This function copies the value in member estop
 * @param _estop New value to be copied in member estop
 */
void ros2_interface::msg::ADCTrajectory::estop(
        const ros2_interface::msg::EStop& _estop)
{
    m_estop = _estop;
}

/*!
 * @brief This function moves the value in member estop
 * @param _estop New value to be moved in member estop
 */
void ros2_interface::msg::ADCTrajectory::estop(
        ros2_interface::msg::EStop&& _estop)
{
    m_estop = std::move(_estop);
}

/*!
 * @brief This function returns a constant reference to member estop
 * @return Constant reference to member estop
 */
const ros2_interface::msg::EStop& ros2_interface::msg::ADCTrajectory::estop() const
{
    return m_estop;
}

/*!
 * @brief This function returns a reference to member estop
 * @return Reference to member estop
 */
ros2_interface::msg::EStop& ros2_interface::msg::ADCTrajectory::estop()
{
    return m_estop;
}
/*!
 * @brief This function sets a value in member is_replan
 * @param _is_replan New value for member is_replan
 */
void ros2_interface::msg::ADCTrajectory::is_replan(
        bool _is_replan)
{
    m_is_replan = _is_replan;
}

/*!
 * @brief This function returns the value of member is_replan
 * @return Value of member is_replan
 */
bool ros2_interface::msg::ADCTrajectory::is_replan() const
{
    return m_is_replan;
}

/*!
 * @brief This function returns a reference to member is_replan
 * @return Reference to member is_replan
 */
bool& ros2_interface::msg::ADCTrajectory::is_replan()
{
    return m_is_replan;
}

/*!
 * @brief This function copies the value in member replan_reason
 * @param _replan_reason New value to be copied in member replan_reason
 */
void ros2_interface::msg::ADCTrajectory::replan_reason(
        const std::string& _replan_reason)
{
    m_replan_reason = _replan_reason;
}

/*!
 * @brief This function moves the value in member replan_reason
 * @param _replan_reason New value to be moved in member replan_reason
 */
void ros2_interface::msg::ADCTrajectory::replan_reason(
        std::string&& _replan_reason)
{
    m_replan_reason = std::move(_replan_reason);
}

/*!
 * @brief This function returns a constant reference to member replan_reason
 * @return Constant reference to member replan_reason
 */
const std::string& ros2_interface::msg::ADCTrajectory::replan_reason() const
{
    return m_replan_reason;
}

/*!
 * @brief This function returns a reference to member replan_reason
 * @return Reference to member replan_reason
 */
std::string& ros2_interface::msg::ADCTrajectory::replan_reason()
{
    return m_replan_reason;
}


size_t ros2_interface::msg::ADCTrajectory::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ros2_interface_msg_ADCTrajectory_max_key_cdr_typesize;
}

bool ros2_interface::msg::ADCTrajectory::isKeyDefined()
{
    return false;
}

void ros2_interface::msg::ADCTrajectory::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



