// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DiagnosticArray.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "DiagnosticArray.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define ros2_interface_msg_DiagnosticStatus_max_cdr_typesize 53064ULL;
#define ros2_interface_msg_KeyValues_max_cdr_typesize 520ULL;
#define ros2_interface_msg_Time_max_cdr_typesize 8ULL;
#define ros2_interface_msg_Header_max_cdr_typesize 272ULL;
#define ros2_interface_msg_DiagnosticArray_max_cdr_typesize 5306676ULL;
#define ros2_interface_msg_DiagnosticStatus_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_KeyValues_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_Time_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_Header_max_key_cdr_typesize 0ULL;
#define ros2_interface_msg_DiagnosticArray_max_key_cdr_typesize 0ULL;

ros2_interface::msg::DiagnosticArray::DiagnosticArray()
{
    // ros2_interface::msg::Header m_header

    // sequence<ros2_interface::msg::DiagnosticStatus> m_status


}

ros2_interface::msg::DiagnosticArray::~DiagnosticArray()
{


}

ros2_interface::msg::DiagnosticArray::DiagnosticArray(
        const DiagnosticArray& x)
{
    m_header = x.m_header;
    m_status = x.m_status;
}

ros2_interface::msg::DiagnosticArray::DiagnosticArray(
        DiagnosticArray&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_status = std::move(x.m_status);
}

ros2_interface::msg::DiagnosticArray& ros2_interface::msg::DiagnosticArray::operator =(
        const DiagnosticArray& x)
{

    m_header = x.m_header;
    m_status = x.m_status;

    return *this;
}

ros2_interface::msg::DiagnosticArray& ros2_interface::msg::DiagnosticArray::operator =(
        DiagnosticArray&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_status = std::move(x.m_status);

    return *this;
}

bool ros2_interface::msg::DiagnosticArray::operator ==(
        const DiagnosticArray& x) const
{

    return (m_header == x.m_header && m_status == x.m_status);
}

bool ros2_interface::msg::DiagnosticArray::operator !=(
        const DiagnosticArray& x) const
{
    return !(*this == x);
}

size_t ros2_interface::msg::DiagnosticArray::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ros2_interface_msg_DiagnosticArray_max_cdr_typesize;
}

size_t ros2_interface::msg::DiagnosticArray::getCdrSerializedSize(
        const ros2_interface::msg::DiagnosticArray& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += ros2_interface::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.status().size(); ++a)
    {
        current_alignment += ros2_interface::msg::DiagnosticStatus::getCdrSerializedSize(data.status().at(a), current_alignment);}


    return current_alignment - initial_alignment;
}

void ros2_interface::msg::DiagnosticArray::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_status;

}

void ros2_interface::msg::DiagnosticArray::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_status;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void ros2_interface::msg::DiagnosticArray::header(
        const ros2_interface::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void ros2_interface::msg::DiagnosticArray::header(
        ros2_interface::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const ros2_interface::msg::Header& ros2_interface::msg::DiagnosticArray::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
ros2_interface::msg::Header& ros2_interface::msg::DiagnosticArray::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member status
 * @param _status New value to be copied in member status
 */
void ros2_interface::msg::DiagnosticArray::status(
        const std::vector<ros2_interface::msg::DiagnosticStatus>& _status)
{
    m_status = _status;
}

/*!
 * @brief This function moves the value in member status
 * @param _status New value to be moved in member status
 */
void ros2_interface::msg::DiagnosticArray::status(
        std::vector<ros2_interface::msg::DiagnosticStatus>&& _status)
{
    m_status = std::move(_status);
}

/*!
 * @brief This function returns a constant reference to member status
 * @return Constant reference to member status
 */
const std::vector<ros2_interface::msg::DiagnosticStatus>& ros2_interface::msg::DiagnosticArray::status() const
{
    return m_status;
}

/*!
 * @brief This function returns a reference to member status
 * @return Reference to member status
 */
std::vector<ros2_interface::msg::DiagnosticStatus>& ros2_interface::msg::DiagnosticArray::status()
{
    return m_status;
}


size_t ros2_interface::msg::DiagnosticArray::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return ros2_interface_msg_DiagnosticArray_max_key_cdr_typesize;
}

bool ros2_interface::msg::DiagnosticArray::isKeyDefined()
{
    return false;
}

void ros2_interface::msg::DiagnosticArray::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



