// Generated by gencpp from file ros_interface/WxAppControl.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_WXAPPCONTROL_H
#define ROS_INTERFACE_MESSAGE_WXAPPCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct WxAppControl_
{
  typedef WxAppControl_<ContainerAllocator> Type;

  WxAppControl_()
    : header()
    , value()  {
    }
  WxAppControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::ros_interface::WxAppControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::WxAppControl_<ContainerAllocator> const> ConstPtr;

}; // struct WxAppControl_

typedef ::ros_interface::WxAppControl_<std::allocator<void> > WxAppControl;

typedef boost::shared_ptr< ::ros_interface::WxAppControl > WxAppControlPtr;
typedef boost::shared_ptr< ::ros_interface::WxAppControl const> WxAppControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::WxAppControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::WxAppControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::WxAppControl_<ContainerAllocator1> & lhs, const ::ros_interface::WxAppControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::WxAppControl_<ContainerAllocator1> & lhs, const ::ros_interface::WxAppControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::WxAppControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::WxAppControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::WxAppControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::WxAppControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::WxAppControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::WxAppControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::WxAppControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22266ff9b4f762c77f0ee04338c1603a";
  }

  static const char* value(const ::ros_interface::WxAppControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22266ff9b4f762c7ULL;
  static const uint64_t static_value2 = 0x7f0ee04338c1603aULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::WxAppControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/WxAppControl";
  }

  static const char* value(const ::ros_interface::WxAppControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::WxAppControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string value\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ros_interface::WxAppControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::WxAppControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WxAppControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::WxAppControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::WxAppControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_WXAPPCONTROL_H
