// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/planning/src/proto/planning_conf.proto

#include "modules/planning/src/proto/planning_conf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_modules_2fcommon_2fbase_5fmessage_2fmessage_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_Message_modules_2fcommon_2fbase_5fmessage_2fmessage_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_modules_2fcommon_2fdata_2fvehicle_5fparam_2fproto_2fvehicle_5fparam_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_VehicleParam_modules_2fcommon_2fdata_2fvehicle_5fparam_2fproto_2fvehicle_5fparam_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_modules_2fplanning_2fsrc_2fproto_2fdriving_2flattice_5fplanner_5fconf_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_LatticePlannerConf_modules_2fplanning_2fsrc_2fproto_2fdriving_2flattice_5fplanner_5fconf_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_modules_2fplanning_2fsrc_2fproto_2fparking_2fparking_5fconf_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_ParkingConf_modules_2fplanning_2fsrc_2fproto_2fparking_2fparking_5fconf_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto;
namespace legion {
namespace planning {
class PlanningConfDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PlanningConf> _instance;
} _PlanningConf_default_instance_;
class StatusConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<StatusConfig> _instance;
} _StatusConfig_default_instance_;
}  // namespace planning
}  // namespace legion
static void InitDefaultsscc_info_PlanningConf_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::legion::planning::_PlanningConf_default_instance_;
    new (ptr) ::legion::planning::PlanningConf();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_PlanningConf_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 5, 0, InitDefaultsscc_info_PlanningConf_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto}, {
      &scc_info_Message_modules_2fcommon_2fbase_5fmessage_2fmessage_2eproto.base,
      &scc_info_LatticePlannerConf_modules_2fplanning_2fsrc_2fproto_2fdriving_2flattice_5fplanner_5fconf_2eproto.base,
      &scc_info_ParkingConf_modules_2fplanning_2fsrc_2fproto_2fparking_2fparking_5fconf_2eproto.base,
      &scc_info_VehicleParam_modules_2fcommon_2fdata_2fvehicle_5fparam_2fproto_2fvehicle_5fparam_2eproto.base,
      &scc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto.base,}};

static void InitDefaultsscc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::legion::planning::_StatusConfig_default_instance_;
    new (ptr) ::legion::planning::StatusConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, app_name_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, description_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, log_file_path_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, log_level_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, logging_data_enable_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_log_debug_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, produce_planning_command_duration_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, publish_planning_command_duration_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, use_system_timestamp_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_local_map_topic_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_elevation_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, min_speed_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, threshold_static_speed_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, threshold_static_speed_self_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, path_density_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, look_forward_time_sec_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, look_forward_long_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, look_forward_short_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, look_backward_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, look_forward_extend_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, reference_line_stitch_overlap_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_lane_change_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_swerving_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_following_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_cutin_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_traffic_light_behavior_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_stop_sign_behavior_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, enable_inward_outward_behavior_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, baselen_collison_check_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, speedcoeff_collision_check_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, map_spline_order_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, map_match_error_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, lane_match_tolerance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, norm_acceleration_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, norm_deceleration_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, anchor_sampling_step_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, knots_sampling_step_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, lateral_bound_limit_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, safe_width_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, safe_length_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, safe_width_lower_limit_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, safe_length_lower_limit_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, safe_dis_speed_lower_limit_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, safe_dis_speed_upper_limit_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, emergency_time_interval_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, emergency_lower_limit_length_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, decision_yield_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, yield_offset_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, virtual_length_max_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, messages_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, lattice_planner_conf_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, parking_conf_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, vehicle_param_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::PlanningConf, status_),
  0,
  1,
  2,
  8,
  9,
  10,
  13,
  14,
  11,
  12,
  25,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  53,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  3,
  4,
  5,
  6,
  7,
  PROTOBUF_FIELD_OFFSET(::legion::planning::StatusConfig, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::legion::planning::StatusConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::legion::planning::StatusConfig, status_detect_duration_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 59, sizeof(::legion::planning::PlanningConf)},
  { 113, 119, sizeof(::legion::planning::StatusConfig)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::legion::planning::_PlanningConf_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::legion::planning::_StatusConfig_default_instance_),
};

const char descriptor_table_protodef_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n.modules/planning/src/proto/planning_co"
  "nf.proto\022\017legion.planning\032)modules/commo"
  "n/base_message/message.proto\032=modules/pl"
  "anning/src/proto/driving/lattice_planner"
  "_conf.proto\0325modules/planning/src/proto/"
  "parking/parking_conf.proto\032;modules/comm"
  "on/data/vehicle_param/proto/vehicle_para"
  "m.proto\"\372\r\n\014PlanningConf\022\022\n\010app_name\030\001 \001"
  "(\t:\000\022\025\n\013description\030\002 \001(\t:\000\022\027\n\rlog_file_"
  "path\030\003 \001(\t:\000\022\024\n\tlog_level\030\004 \001(\005:\0010\022\"\n\023lo"
  "gging_data_enable\030\005 \001(\010:\005false\022\037\n\020enable"
  "_log_debug\030\006 \001(\010:\005false\022,\n!produce_plann"
  "ing_command_duration\030\007 \001(\001:\0010\022,\n!publish"
  "_planning_command_duration\030\010 \001(\001:\0010\022\034\n\024u"
  "se_system_timestamp\030\t \001(\010\022\036\n\026enable_loca"
  "l_map_topic\030\n \001(\010\022\030\n\020enable_elevation\030\013 "
  "\001(\010\022\021\n\tmin_speed\030\014 \001(\001\022\036\n\026threshold_stat"
  "ic_speed\030\r \001(\001\022#\n\033threshold_static_speed"
  "_self\030\016 \001(\001\022\024\n\014path_density\030\017 \001(\001\022\035\n\025loo"
  "k_forward_time_sec\030\020 \001(\001\022\"\n\032look_forward"
  "_long_distance\030\021 \001(\001\022#\n\033look_forward_sho"
  "rt_distance\030\022 \001(\001\022\036\n\026look_backward_dista"
  "nce\030\023 \001(\001\022$\n\034look_forward_extend_distanc"
  "e\030\024 \001(\001\022.\n&reference_line_stitch_overlap"
  "_distance\030\025 \001(\001\022\032\n\022enable_lane_change\030\026 "
  "\001(\010\022\027\n\017enable_swerving\030\027 \001(\010\022\030\n\020enable_f"
  "ollowing\030\030 \001(\010\022\024\n\014enable_cutin\030\031 \001(\010\022%\n\035"
  "enable_traffic_light_behavior\030\032 \001(\010\022!\n\031e"
  "nable_stop_sign_behavior\030\033 \001(\010\022&\n\036enable"
  "_inward_outward_behavior\030\034 \001(\010\022\036\n\026basele"
  "n_collison_check\030\035 \001(\001\022\"\n\032speedcoeff_col"
  "lision_check\030\036 \001(\001\022\030\n\020map_spline_order\030\037"
  " \001(\005\022\027\n\017map_match_error\030  \001(\001\022\034\n\024lane_ma"
  "tch_tolerance\030! \001(\001\022\031\n\021norm_acceleration"
  "\030\" \001(\001\022\031\n\021norm_deceleration\030# \001(\001\022\034\n\024anc"
  "hor_sampling_step\030$ \001(\001\022\033\n\023knots_samplin"
  "g_step\030% \001(\001\022\033\n\023lateral_bound_limit\030& \001("
  "\001\022\022\n\nsafe_width\030\' \001(\001\022\023\n\013safe_length\030( \001"
  "(\001\022\036\n\026safe_width_lower_limit\030) \001(\001\022\037\n\027sa"
  "fe_length_lower_limit\030* \001(\001\022\"\n\032safe_dis_"
  "speed_lower_limit\030+ \001(\001\022\"\n\032safe_dis_spee"
  "d_upper_limit\030, \001(\001\022\037\n\027emergency_time_in"
  "terval\030- \001(\001\022$\n\034emergency_lower_limit_le"
  "ngth\030. \001(\001\022\037\n\027decision_yield_distance\030/ "
  "\001(\001\022\024\n\014yield_offset\0300 \001(\001\022\032\n\022virtual_len"
  "gth_max\0301 \001(\001\022(\n\010messages\0303 \001(\0132\026.legion"
  ".common.Message\022A\n\024lattice_planner_conf\030"
  "4 \001(\0132#.legion.planning.LatticePlannerCo"
  "nf\0222\n\014parking_conf\0305 \001(\0132\034.legion.planni"
  "ng.ParkingConf\0225\n\rvehicle_param\0306 \001(\0132\036."
  "legion.interface.VehicleParam\022-\n\006status\030"
  "7 \001(\0132\035.legion.planning.StatusConfig\".\n\014"
  "StatusConfig\022\036\n\026status_detect_duration\030\001"
  " \001(\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto_deps[4] = {
  &::descriptor_table_modules_2fcommon_2fbase_5fmessage_2fmessage_2eproto,
  &::descriptor_table_modules_2fcommon_2fdata_2fvehicle_5fparam_2fproto_2fvehicle_5fparam_2eproto,
  &::descriptor_table_modules_2fplanning_2fsrc_2fproto_2fdriving_2flattice_5fplanner_5fconf_2eproto,
  &::descriptor_table_modules_2fplanning_2fsrc_2fproto_2fparking_2fparking_5fconf_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto_sccs[2] = {
  &scc_info_PlanningConf_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto.base,
  &scc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto = {
  false, false, descriptor_table_protodef_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto, "modules/planning/src/proto/planning_conf.proto", 2124,
  &descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto_once, descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto_sccs, descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto_deps, 2, 4,
  schemas, file_default_instances, TableStruct_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto::offsets,
  file_level_metadata_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto, 2, file_level_enum_descriptors_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto, file_level_service_descriptors_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto)), true);
namespace legion {
namespace planning {

// ===================================================================

class PlanningConf::_Internal {
 public:
  using HasBits = decltype(std::declval<PlanningConf>()._has_bits_);
  static void set_has_app_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_description(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_log_file_path(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_log_level(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_logging_data_enable(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_enable_log_debug(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_produce_planning_command_duration(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_publish_planning_command_duration(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static void set_has_use_system_timestamp(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_enable_local_map_topic(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_enable_elevation(HasBits* has_bits) {
    (*has_bits)[0] |= 33554432u;
  }
  static void set_has_min_speed(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
  static void set_has_threshold_static_speed(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static void set_has_threshold_static_speed_self(HasBits* has_bits) {
    (*has_bits)[0] |= 131072u;
  }
  static void set_has_path_density(HasBits* has_bits) {
    (*has_bits)[0] |= 262144u;
  }
  static void set_has_look_forward_time_sec(HasBits* has_bits) {
    (*has_bits)[0] |= 524288u;
  }
  static void set_has_look_forward_long_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 1048576u;
  }
  static void set_has_look_forward_short_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 2097152u;
  }
  static void set_has_look_backward_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 4194304u;
  }
  static void set_has_look_forward_extend_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 8388608u;
  }
  static void set_has_reference_line_stitch_overlap_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 16777216u;
  }
  static void set_has_enable_lane_change(HasBits* has_bits) {
    (*has_bits)[0] |= 67108864u;
  }
  static void set_has_enable_swerving(HasBits* has_bits) {
    (*has_bits)[0] |= 134217728u;
  }
  static void set_has_enable_following(HasBits* has_bits) {
    (*has_bits)[0] |= 268435456u;
  }
  static void set_has_enable_cutin(HasBits* has_bits) {
    (*has_bits)[0] |= 536870912u;
  }
  static void set_has_enable_traffic_light_behavior(HasBits* has_bits) {
    (*has_bits)[0] |= 1073741824u;
  }
  static void set_has_enable_stop_sign_behavior(HasBits* has_bits) {
    (*has_bits)[0] |= 2147483648u;
  }
  static void set_has_enable_inward_outward_behavior(HasBits* has_bits) {
    (*has_bits)[1] |= 1u;
  }
  static void set_has_baselen_collison_check(HasBits* has_bits) {
    (*has_bits)[1] |= 2u;
  }
  static void set_has_speedcoeff_collision_check(HasBits* has_bits) {
    (*has_bits)[1] |= 4u;
  }
  static void set_has_map_spline_order(HasBits* has_bits) {
    (*has_bits)[1] |= 2097152u;
  }
  static void set_has_map_match_error(HasBits* has_bits) {
    (*has_bits)[1] |= 8u;
  }
  static void set_has_lane_match_tolerance(HasBits* has_bits) {
    (*has_bits)[1] |= 16u;
  }
  static void set_has_norm_acceleration(HasBits* has_bits) {
    (*has_bits)[1] |= 32u;
  }
  static void set_has_norm_deceleration(HasBits* has_bits) {
    (*has_bits)[1] |= 64u;
  }
  static void set_has_anchor_sampling_step(HasBits* has_bits) {
    (*has_bits)[1] |= 128u;
  }
  static void set_has_knots_sampling_step(HasBits* has_bits) {
    (*has_bits)[1] |= 256u;
  }
  static void set_has_lateral_bound_limit(HasBits* has_bits) {
    (*has_bits)[1] |= 512u;
  }
  static void set_has_safe_width(HasBits* has_bits) {
    (*has_bits)[1] |= 1024u;
  }
  static void set_has_safe_length(HasBits* has_bits) {
    (*has_bits)[1] |= 2048u;
  }
  static void set_has_safe_width_lower_limit(HasBits* has_bits) {
    (*has_bits)[1] |= 4096u;
  }
  static void set_has_safe_length_lower_limit(HasBits* has_bits) {
    (*has_bits)[1] |= 8192u;
  }
  static void set_has_safe_dis_speed_lower_limit(HasBits* has_bits) {
    (*has_bits)[1] |= 16384u;
  }
  static void set_has_safe_dis_speed_upper_limit(HasBits* has_bits) {
    (*has_bits)[1] |= 32768u;
  }
  static void set_has_emergency_time_interval(HasBits* has_bits) {
    (*has_bits)[1] |= 65536u;
  }
  static void set_has_emergency_lower_limit_length(HasBits* has_bits) {
    (*has_bits)[1] |= 131072u;
  }
  static void set_has_decision_yield_distance(HasBits* has_bits) {
    (*has_bits)[1] |= 262144u;
  }
  static void set_has_yield_offset(HasBits* has_bits) {
    (*has_bits)[1] |= 524288u;
  }
  static void set_has_virtual_length_max(HasBits* has_bits) {
    (*has_bits)[1] |= 1048576u;
  }
  static const ::legion::common::Message& messages(const PlanningConf* msg);
  static void set_has_messages(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::legion::planning::LatticePlannerConf& lattice_planner_conf(const PlanningConf* msg);
  static void set_has_lattice_planner_conf(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::legion::planning::ParkingConf& parking_conf(const PlanningConf* msg);
  static void set_has_parking_conf(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static const ::legion::interface::VehicleParam& vehicle_param(const PlanningConf* msg);
  static void set_has_vehicle_param(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static const ::legion::planning::StatusConfig& status(const PlanningConf* msg);
  static void set_has_status(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
};

const ::legion::common::Message&
PlanningConf::_Internal::messages(const PlanningConf* msg) {
  return *msg->messages_;
}
const ::legion::planning::LatticePlannerConf&
PlanningConf::_Internal::lattice_planner_conf(const PlanningConf* msg) {
  return *msg->lattice_planner_conf_;
}
const ::legion::planning::ParkingConf&
PlanningConf::_Internal::parking_conf(const PlanningConf* msg) {
  return *msg->parking_conf_;
}
const ::legion::interface::VehicleParam&
PlanningConf::_Internal::vehicle_param(const PlanningConf* msg) {
  return *msg->vehicle_param_;
}
const ::legion::planning::StatusConfig&
PlanningConf::_Internal::status(const PlanningConf* msg) {
  return *msg->status_;
}
void PlanningConf::clear_messages() {
  if (messages_ != nullptr) messages_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
void PlanningConf::clear_lattice_planner_conf() {
  if (lattice_planner_conf_ != nullptr) lattice_planner_conf_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
void PlanningConf::clear_parking_conf() {
  if (parking_conf_ != nullptr) parking_conf_->Clear();
  _has_bits_[0] &= ~0x00000020u;
}
void PlanningConf::clear_vehicle_param() {
  if (vehicle_param_ != nullptr) vehicle_param_->Clear();
  _has_bits_[0] &= ~0x00000040u;
}
PlanningConf::PlanningConf(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.planning.PlanningConf)
}
PlanningConf::PlanningConf(const PlanningConf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  app_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_app_name()) {
    app_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_app_name(), 
      GetArena());
  }
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_description()) {
    description_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_description(), 
      GetArena());
  }
  log_file_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_log_file_path()) {
    log_file_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_log_file_path(), 
      GetArena());
  }
  if (from._internal_has_messages()) {
    messages_ = new ::legion::common::Message(*from.messages_);
  } else {
    messages_ = nullptr;
  }
  if (from._internal_has_lattice_planner_conf()) {
    lattice_planner_conf_ = new ::legion::planning::LatticePlannerConf(*from.lattice_planner_conf_);
  } else {
    lattice_planner_conf_ = nullptr;
  }
  if (from._internal_has_parking_conf()) {
    parking_conf_ = new ::legion::planning::ParkingConf(*from.parking_conf_);
  } else {
    parking_conf_ = nullptr;
  }
  if (from._internal_has_vehicle_param()) {
    vehicle_param_ = new ::legion::interface::VehicleParam(*from.vehicle_param_);
  } else {
    vehicle_param_ = nullptr;
  }
  if (from._internal_has_status()) {
    status_ = new ::legion::planning::StatusConfig(*from.status_);
  } else {
    status_ = nullptr;
  }
  ::memcpy(&log_level_, &from.log_level_,
    static_cast<size_t>(reinterpret_cast<char*>(&map_spline_order_) -
    reinterpret_cast<char*>(&log_level_)) + sizeof(map_spline_order_));
  // @@protoc_insertion_point(copy_constructor:legion.planning.PlanningConf)
}

void PlanningConf::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PlanningConf_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto.base);
  app_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  log_file_path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&messages_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&map_spline_order_) -
      reinterpret_cast<char*>(&messages_)) + sizeof(map_spline_order_));
}

PlanningConf::~PlanningConf() {
  // @@protoc_insertion_point(destructor:legion.planning.PlanningConf)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PlanningConf::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  app_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  log_file_path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete messages_;
  if (this != internal_default_instance()) delete lattice_planner_conf_;
  if (this != internal_default_instance()) delete parking_conf_;
  if (this != internal_default_instance()) delete vehicle_param_;
  if (this != internal_default_instance()) delete status_;
}

void PlanningConf::ArenaDtor(void* object) {
  PlanningConf* _this = reinterpret_cast< PlanningConf* >(object);
  (void)_this;
}
void PlanningConf::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlanningConf::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PlanningConf& PlanningConf::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PlanningConf_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto.base);
  return *internal_default_instance();
}


void PlanningConf::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.planning.PlanningConf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      app_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      description_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      log_file_path_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(messages_ != nullptr);
      messages_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(lattice_planner_conf_ != nullptr);
      lattice_planner_conf_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(parking_conf_ != nullptr);
      parking_conf_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      GOOGLE_DCHECK(vehicle_param_ != nullptr);
      vehicle_param_->Clear();
    }
    if (cached_has_bits & 0x00000080u) {
      GOOGLE_DCHECK(status_ != nullptr);
      status_->Clear();
    }
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&log_level_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&min_speed_) -
        reinterpret_cast<char*>(&log_level_)) + sizeof(min_speed_));
  }
  if (cached_has_bits & 0x00ff0000u) {
    ::memset(&threshold_static_speed_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&look_forward_extend_distance_) -
        reinterpret_cast<char*>(&threshold_static_speed_)) + sizeof(look_forward_extend_distance_));
  }
  if (cached_has_bits & 0xff000000u) {
    ::memset(&reference_line_stitch_overlap_distance_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&enable_stop_sign_behavior_) -
        reinterpret_cast<char*>(&reference_line_stitch_overlap_distance_)) + sizeof(enable_stop_sign_behavior_));
  }
  cached_has_bits = _has_bits_[1];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&enable_inward_outward_behavior_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&anchor_sampling_step_) -
        reinterpret_cast<char*>(&enable_inward_outward_behavior_)) + sizeof(anchor_sampling_step_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&knots_sampling_step_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&safe_dis_speed_upper_limit_) -
        reinterpret_cast<char*>(&knots_sampling_step_)) + sizeof(safe_dis_speed_upper_limit_));
  }
  if (cached_has_bits & 0x003f0000u) {
    ::memset(&emergency_time_interval_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&map_spline_order_) -
        reinterpret_cast<char*>(&emergency_time_interval_)) + sizeof(map_spline_order_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlanningConf::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string app_name = 1 [default = ""];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_app_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "legion.planning.PlanningConf.app_name");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string description = 2 [default = ""];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_description();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "legion.planning.PlanningConf.description");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string log_file_path = 3 [default = ""];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_log_file_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "legion.planning.PlanningConf.log_file_path");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional int32 log_level = 4 [default = 0];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_log_level(&_has_bits_);
          log_level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool logging_data_enable = 5 [default = false];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_logging_data_enable(&_has_bits_);
          logging_data_enable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_log_debug = 6 [default = false];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_enable_log_debug(&_has_bits_);
          enable_log_debug_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double produce_planning_command_duration = 7 [default = 0];
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          _Internal::set_has_produce_planning_command_duration(&_has_bits_);
          produce_planning_command_duration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double publish_planning_command_duration = 8 [default = 0];
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          _Internal::set_has_publish_planning_command_duration(&_has_bits_);
          publish_planning_command_duration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional bool use_system_timestamp = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          _Internal::set_has_use_system_timestamp(&_has_bits_);
          use_system_timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_local_map_topic = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          _Internal::set_has_enable_local_map_topic(&_has_bits_);
          enable_local_map_topic_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_elevation = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          _Internal::set_has_enable_elevation(&_has_bits_);
          enable_elevation_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double min_speed = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 97)) {
          _Internal::set_has_min_speed(&_has_bits_);
          min_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double threshold_static_speed = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 105)) {
          _Internal::set_has_threshold_static_speed(&_has_bits_);
          threshold_static_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double threshold_static_speed_self = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 113)) {
          _Internal::set_has_threshold_static_speed_self(&_has_bits_);
          threshold_static_speed_self_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double path_density = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 121)) {
          _Internal::set_has_path_density(&_has_bits_);
          path_density_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double look_forward_time_sec = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 129)) {
          _Internal::set_has_look_forward_time_sec(&_has_bits_);
          look_forward_time_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double look_forward_long_distance = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 137)) {
          _Internal::set_has_look_forward_long_distance(&_has_bits_);
          look_forward_long_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double look_forward_short_distance = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 145)) {
          _Internal::set_has_look_forward_short_distance(&_has_bits_);
          look_forward_short_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double look_backward_distance = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 153)) {
          _Internal::set_has_look_backward_distance(&_has_bits_);
          look_backward_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double look_forward_extend_distance = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 161)) {
          _Internal::set_has_look_forward_extend_distance(&_has_bits_);
          look_forward_extend_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double reference_line_stitch_overlap_distance = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 169)) {
          _Internal::set_has_reference_line_stitch_overlap_distance(&_has_bits_);
          reference_line_stitch_overlap_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional bool enable_lane_change = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 176)) {
          _Internal::set_has_enable_lane_change(&_has_bits_);
          enable_lane_change_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_swerving = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 184)) {
          _Internal::set_has_enable_swerving(&_has_bits_);
          enable_swerving_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_following = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 192)) {
          _Internal::set_has_enable_following(&_has_bits_);
          enable_following_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_cutin = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 200)) {
          _Internal::set_has_enable_cutin(&_has_bits_);
          enable_cutin_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_traffic_light_behavior = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 208)) {
          _Internal::set_has_enable_traffic_light_behavior(&_has_bits_);
          enable_traffic_light_behavior_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_stop_sign_behavior = 27;
      case 27:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 216)) {
          _Internal::set_has_enable_stop_sign_behavior(&_has_bits_);
          enable_stop_sign_behavior_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_inward_outward_behavior = 28;
      case 28:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 224)) {
          _Internal::set_has_enable_inward_outward_behavior(&_has_bits_);
          enable_inward_outward_behavior_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double baselen_collison_check = 29;
      case 29:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 233)) {
          _Internal::set_has_baselen_collison_check(&_has_bits_);
          baselen_collison_check_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double speedcoeff_collision_check = 30;
      case 30:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 241)) {
          _Internal::set_has_speedcoeff_collision_check(&_has_bits_);
          speedcoeff_collision_check_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional int32 map_spline_order = 31;
      case 31:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 248)) {
          _Internal::set_has_map_spline_order(&_has_bits_);
          map_spline_order_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double map_match_error = 32;
      case 32:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 1)) {
          _Internal::set_has_map_match_error(&_has_bits_);
          map_match_error_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lane_match_tolerance = 33;
      case 33:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          _Internal::set_has_lane_match_tolerance(&_has_bits_);
          lane_match_tolerance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double norm_acceleration = 34;
      case 34:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          _Internal::set_has_norm_acceleration(&_has_bits_);
          norm_acceleration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double norm_deceleration = 35;
      case 35:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          _Internal::set_has_norm_deceleration(&_has_bits_);
          norm_deceleration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double anchor_sampling_step = 36;
      case 36:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          _Internal::set_has_anchor_sampling_step(&_has_bits_);
          anchor_sampling_step_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double knots_sampling_step = 37;
      case 37:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          _Internal::set_has_knots_sampling_step(&_has_bits_);
          knots_sampling_step_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lateral_bound_limit = 38;
      case 38:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 49)) {
          _Internal::set_has_lateral_bound_limit(&_has_bits_);
          lateral_bound_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double safe_width = 39;
      case 39:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          _Internal::set_has_safe_width(&_has_bits_);
          safe_width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double safe_length = 40;
      case 40:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          _Internal::set_has_safe_length(&_has_bits_);
          safe_length_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double safe_width_lower_limit = 41;
      case 41:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 73)) {
          _Internal::set_has_safe_width_lower_limit(&_has_bits_);
          safe_width_lower_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double safe_length_lower_limit = 42;
      case 42:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          _Internal::set_has_safe_length_lower_limit(&_has_bits_);
          safe_length_lower_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double safe_dis_speed_lower_limit = 43;
      case 43:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 89)) {
          _Internal::set_has_safe_dis_speed_lower_limit(&_has_bits_);
          safe_dis_speed_lower_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double safe_dis_speed_upper_limit = 44;
      case 44:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 97)) {
          _Internal::set_has_safe_dis_speed_upper_limit(&_has_bits_);
          safe_dis_speed_upper_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double emergency_time_interval = 45;
      case 45:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 105)) {
          _Internal::set_has_emergency_time_interval(&_has_bits_);
          emergency_time_interval_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double emergency_lower_limit_length = 46;
      case 46:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 113)) {
          _Internal::set_has_emergency_lower_limit_length(&_has_bits_);
          emergency_lower_limit_length_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double decision_yield_distance = 47;
      case 47:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 121)) {
          _Internal::set_has_decision_yield_distance(&_has_bits_);
          decision_yield_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double yield_offset = 48;
      case 48:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 129)) {
          _Internal::set_has_yield_offset(&_has_bits_);
          yield_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double virtual_length_max = 49;
      case 49:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 137)) {
          _Internal::set_has_virtual_length_max(&_has_bits_);
          virtual_length_max_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional .legion.common.Message messages = 51;
      case 51:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          ptr = ctx->ParseMessage(_internal_mutable_messages(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .legion.planning.LatticePlannerConf lattice_planner_conf = 52;
      case 52:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ctx->ParseMessage(_internal_mutable_lattice_planner_conf(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .legion.planning.ParkingConf parking_conf = 53;
      case 53:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 170)) {
          ptr = ctx->ParseMessage(_internal_mutable_parking_conf(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .legion.interface.VehicleParam vehicle_param = 54;
      case 54:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 178)) {
          ptr = ctx->ParseMessage(_internal_mutable_vehicle_param(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .legion.planning.StatusConfig status = 55;
      case 55:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 186)) {
          ptr = ctx->ParseMessage(_internal_mutable_status(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlanningConf::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:legion.planning.PlanningConf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string app_name = 1 [default = ""];
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_app_name().data(), static_cast<int>(this->_internal_app_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "legion.planning.PlanningConf.app_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_app_name(), target);
  }

  // optional string description = 2 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "legion.planning.PlanningConf.description");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_description(), target);
  }

  // optional string log_file_path = 3 [default = ""];
  if (cached_has_bits & 0x00000004u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_log_file_path().data(), static_cast<int>(this->_internal_log_file_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "legion.planning.PlanningConf.log_file_path");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_log_file_path(), target);
  }

  // optional int32 log_level = 4 [default = 0];
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_log_level(), target);
  }

  // optional bool logging_data_enable = 5 [default = false];
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_logging_data_enable(), target);
  }

  // optional bool enable_log_debug = 6 [default = false];
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_enable_log_debug(), target);
  }

  // optional double produce_planning_command_duration = 7 [default = 0];
  if (cached_has_bits & 0x00002000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_produce_planning_command_duration(), target);
  }

  // optional double publish_planning_command_duration = 8 [default = 0];
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_publish_planning_command_duration(), target);
  }

  // optional bool use_system_timestamp = 9;
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(9, this->_internal_use_system_timestamp(), target);
  }

  // optional bool enable_local_map_topic = 10;
  if (cached_has_bits & 0x00001000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(10, this->_internal_enable_local_map_topic(), target);
  }

  // optional bool enable_elevation = 11;
  if (cached_has_bits & 0x02000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(11, this->_internal_enable_elevation(), target);
  }

  // optional double min_speed = 12;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(12, this->_internal_min_speed(), target);
  }

  // optional double threshold_static_speed = 13;
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(13, this->_internal_threshold_static_speed(), target);
  }

  // optional double threshold_static_speed_self = 14;
  if (cached_has_bits & 0x00020000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(14, this->_internal_threshold_static_speed_self(), target);
  }

  // optional double path_density = 15;
  if (cached_has_bits & 0x00040000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(15, this->_internal_path_density(), target);
  }

  // optional double look_forward_time_sec = 16;
  if (cached_has_bits & 0x00080000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(16, this->_internal_look_forward_time_sec(), target);
  }

  // optional double look_forward_long_distance = 17;
  if (cached_has_bits & 0x00100000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(17, this->_internal_look_forward_long_distance(), target);
  }

  // optional double look_forward_short_distance = 18;
  if (cached_has_bits & 0x00200000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(18, this->_internal_look_forward_short_distance(), target);
  }

  // optional double look_backward_distance = 19;
  if (cached_has_bits & 0x00400000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(19, this->_internal_look_backward_distance(), target);
  }

  // optional double look_forward_extend_distance = 20;
  if (cached_has_bits & 0x00800000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(20, this->_internal_look_forward_extend_distance(), target);
  }

  // optional double reference_line_stitch_overlap_distance = 21;
  if (cached_has_bits & 0x01000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(21, this->_internal_reference_line_stitch_overlap_distance(), target);
  }

  // optional bool enable_lane_change = 22;
  if (cached_has_bits & 0x04000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(22, this->_internal_enable_lane_change(), target);
  }

  // optional bool enable_swerving = 23;
  if (cached_has_bits & 0x08000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(23, this->_internal_enable_swerving(), target);
  }

  // optional bool enable_following = 24;
  if (cached_has_bits & 0x10000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(24, this->_internal_enable_following(), target);
  }

  // optional bool enable_cutin = 25;
  if (cached_has_bits & 0x20000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(25, this->_internal_enable_cutin(), target);
  }

  // optional bool enable_traffic_light_behavior = 26;
  if (cached_has_bits & 0x40000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(26, this->_internal_enable_traffic_light_behavior(), target);
  }

  // optional bool enable_stop_sign_behavior = 27;
  if (cached_has_bits & 0x80000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(27, this->_internal_enable_stop_sign_behavior(), target);
  }

  cached_has_bits = _has_bits_[1];
  // optional bool enable_inward_outward_behavior = 28;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(28, this->_internal_enable_inward_outward_behavior(), target);
  }

  // optional double baselen_collison_check = 29;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(29, this->_internal_baselen_collison_check(), target);
  }

  // optional double speedcoeff_collision_check = 30;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(30, this->_internal_speedcoeff_collision_check(), target);
  }

  // optional int32 map_spline_order = 31;
  if (cached_has_bits & 0x00200000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(31, this->_internal_map_spline_order(), target);
  }

  // optional double map_match_error = 32;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(32, this->_internal_map_match_error(), target);
  }

  // optional double lane_match_tolerance = 33;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(33, this->_internal_lane_match_tolerance(), target);
  }

  // optional double norm_acceleration = 34;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(34, this->_internal_norm_acceleration(), target);
  }

  // optional double norm_deceleration = 35;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(35, this->_internal_norm_deceleration(), target);
  }

  // optional double anchor_sampling_step = 36;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(36, this->_internal_anchor_sampling_step(), target);
  }

  // optional double knots_sampling_step = 37;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(37, this->_internal_knots_sampling_step(), target);
  }

  // optional double lateral_bound_limit = 38;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(38, this->_internal_lateral_bound_limit(), target);
  }

  // optional double safe_width = 39;
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(39, this->_internal_safe_width(), target);
  }

  // optional double safe_length = 40;
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(40, this->_internal_safe_length(), target);
  }

  // optional double safe_width_lower_limit = 41;
  if (cached_has_bits & 0x00001000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(41, this->_internal_safe_width_lower_limit(), target);
  }

  // optional double safe_length_lower_limit = 42;
  if (cached_has_bits & 0x00002000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(42, this->_internal_safe_length_lower_limit(), target);
  }

  // optional double safe_dis_speed_lower_limit = 43;
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(43, this->_internal_safe_dis_speed_lower_limit(), target);
  }

  // optional double safe_dis_speed_upper_limit = 44;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(44, this->_internal_safe_dis_speed_upper_limit(), target);
  }

  // optional double emergency_time_interval = 45;
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(45, this->_internal_emergency_time_interval(), target);
  }

  // optional double emergency_lower_limit_length = 46;
  if (cached_has_bits & 0x00020000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(46, this->_internal_emergency_lower_limit_length(), target);
  }

  // optional double decision_yield_distance = 47;
  if (cached_has_bits & 0x00040000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(47, this->_internal_decision_yield_distance(), target);
  }

  // optional double yield_offset = 48;
  if (cached_has_bits & 0x00080000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(48, this->_internal_yield_offset(), target);
  }

  // optional double virtual_length_max = 49;
  if (cached_has_bits & 0x00100000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(49, this->_internal_virtual_length_max(), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional .legion.common.Message messages = 51;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        51, _Internal::messages(this), target, stream);
  }

  // optional .legion.planning.LatticePlannerConf lattice_planner_conf = 52;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        52, _Internal::lattice_planner_conf(this), target, stream);
  }

  // optional .legion.planning.ParkingConf parking_conf = 53;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        53, _Internal::parking_conf(this), target, stream);
  }

  // optional .legion.interface.VehicleParam vehicle_param = 54;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        54, _Internal::vehicle_param(this), target, stream);
  }

  // optional .legion.planning.StatusConfig status = 55;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        55, _Internal::status(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.planning.PlanningConf)
  return target;
}

size_t PlanningConf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:legion.planning.PlanningConf)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string app_name = 1 [default = ""];
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_app_name());
    }

    // optional string description = 2 [default = ""];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_description());
    }

    // optional string log_file_path = 3 [default = ""];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_log_file_path());
    }

    // optional .legion.common.Message messages = 51;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *messages_);
    }

    // optional .legion.planning.LatticePlannerConf lattice_planner_conf = 52;
    if (cached_has_bits & 0x00000010u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *lattice_planner_conf_);
    }

    // optional .legion.planning.ParkingConf parking_conf = 53;
    if (cached_has_bits & 0x00000020u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *parking_conf_);
    }

    // optional .legion.interface.VehicleParam vehicle_param = 54;
    if (cached_has_bits & 0x00000040u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vehicle_param_);
    }

    // optional .legion.planning.StatusConfig status = 55;
    if (cached_has_bits & 0x00000080u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *status_);
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional int32 log_level = 4 [default = 0];
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_log_level());
    }

    // optional bool logging_data_enable = 5 [default = false];
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 + 1;
    }

    // optional bool enable_log_debug = 6 [default = false];
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 + 1;
    }

    // optional bool use_system_timestamp = 9;
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 + 1;
    }

    // optional bool enable_local_map_topic = 10;
    if (cached_has_bits & 0x00001000u) {
      total_size += 1 + 1;
    }

    // optional double produce_planning_command_duration = 7 [default = 0];
    if (cached_has_bits & 0x00002000u) {
      total_size += 1 + 8;
    }

    // optional double publish_planning_command_duration = 8 [default = 0];
    if (cached_has_bits & 0x00004000u) {
      total_size += 1 + 8;
    }

    // optional double min_speed = 12;
    if (cached_has_bits & 0x00008000u) {
      total_size += 1 + 8;
    }

  }
  if (cached_has_bits & 0x00ff0000u) {
    // optional double threshold_static_speed = 13;
    if (cached_has_bits & 0x00010000u) {
      total_size += 1 + 8;
    }

    // optional double threshold_static_speed_self = 14;
    if (cached_has_bits & 0x00020000u) {
      total_size += 1 + 8;
    }

    // optional double path_density = 15;
    if (cached_has_bits & 0x00040000u) {
      total_size += 1 + 8;
    }

    // optional double look_forward_time_sec = 16;
    if (cached_has_bits & 0x00080000u) {
      total_size += 2 + 8;
    }

    // optional double look_forward_long_distance = 17;
    if (cached_has_bits & 0x00100000u) {
      total_size += 2 + 8;
    }

    // optional double look_forward_short_distance = 18;
    if (cached_has_bits & 0x00200000u) {
      total_size += 2 + 8;
    }

    // optional double look_backward_distance = 19;
    if (cached_has_bits & 0x00400000u) {
      total_size += 2 + 8;
    }

    // optional double look_forward_extend_distance = 20;
    if (cached_has_bits & 0x00800000u) {
      total_size += 2 + 8;
    }

  }
  if (cached_has_bits & 0xff000000u) {
    // optional double reference_line_stitch_overlap_distance = 21;
    if (cached_has_bits & 0x01000000u) {
      total_size += 2 + 8;
    }

    // optional bool enable_elevation = 11;
    if (cached_has_bits & 0x02000000u) {
      total_size += 1 + 1;
    }

    // optional bool enable_lane_change = 22;
    if (cached_has_bits & 0x04000000u) {
      total_size += 2 + 1;
    }

    // optional bool enable_swerving = 23;
    if (cached_has_bits & 0x08000000u) {
      total_size += 2 + 1;
    }

    // optional bool enable_following = 24;
    if (cached_has_bits & 0x10000000u) {
      total_size += 2 + 1;
    }

    // optional bool enable_cutin = 25;
    if (cached_has_bits & 0x20000000u) {
      total_size += 2 + 1;
    }

    // optional bool enable_traffic_light_behavior = 26;
    if (cached_has_bits & 0x40000000u) {
      total_size += 2 + 1;
    }

    // optional bool enable_stop_sign_behavior = 27;
    if (cached_has_bits & 0x80000000u) {
      total_size += 2 + 1;
    }

  }
  cached_has_bits = _has_bits_[1];
  if (cached_has_bits & 0x000000ffu) {
    // optional bool enable_inward_outward_behavior = 28;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 + 1;
    }

    // optional double baselen_collison_check = 29;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 + 8;
    }

    // optional double speedcoeff_collision_check = 30;
    if (cached_has_bits & 0x00000004u) {
      total_size += 2 + 8;
    }

    // optional double map_match_error = 32;
    if (cached_has_bits & 0x00000008u) {
      total_size += 2 + 8;
    }

    // optional double lane_match_tolerance = 33;
    if (cached_has_bits & 0x00000010u) {
      total_size += 2 + 8;
    }

    // optional double norm_acceleration = 34;
    if (cached_has_bits & 0x00000020u) {
      total_size += 2 + 8;
    }

    // optional double norm_deceleration = 35;
    if (cached_has_bits & 0x00000040u) {
      total_size += 2 + 8;
    }

    // optional double anchor_sampling_step = 36;
    if (cached_has_bits & 0x00000080u) {
      total_size += 2 + 8;
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional double knots_sampling_step = 37;
    if (cached_has_bits & 0x00000100u) {
      total_size += 2 + 8;
    }

    // optional double lateral_bound_limit = 38;
    if (cached_has_bits & 0x00000200u) {
      total_size += 2 + 8;
    }

    // optional double safe_width = 39;
    if (cached_has_bits & 0x00000400u) {
      total_size += 2 + 8;
    }

    // optional double safe_length = 40;
    if (cached_has_bits & 0x00000800u) {
      total_size += 2 + 8;
    }

    // optional double safe_width_lower_limit = 41;
    if (cached_has_bits & 0x00001000u) {
      total_size += 2 + 8;
    }

    // optional double safe_length_lower_limit = 42;
    if (cached_has_bits & 0x00002000u) {
      total_size += 2 + 8;
    }

    // optional double safe_dis_speed_lower_limit = 43;
    if (cached_has_bits & 0x00004000u) {
      total_size += 2 + 8;
    }

    // optional double safe_dis_speed_upper_limit = 44;
    if (cached_has_bits & 0x00008000u) {
      total_size += 2 + 8;
    }

  }
  if (cached_has_bits & 0x003f0000u) {
    // optional double emergency_time_interval = 45;
    if (cached_has_bits & 0x00010000u) {
      total_size += 2 + 8;
    }

    // optional double emergency_lower_limit_length = 46;
    if (cached_has_bits & 0x00020000u) {
      total_size += 2 + 8;
    }

    // optional double decision_yield_distance = 47;
    if (cached_has_bits & 0x00040000u) {
      total_size += 2 + 8;
    }

    // optional double yield_offset = 48;
    if (cached_has_bits & 0x00080000u) {
      total_size += 2 + 8;
    }

    // optional double virtual_length_max = 49;
    if (cached_has_bits & 0x00100000u) {
      total_size += 2 + 8;
    }

    // optional int32 map_spline_order = 31;
    if (cached_has_bits & 0x00200000u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_map_spline_order());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PlanningConf::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:legion.planning.PlanningConf)
  GOOGLE_DCHECK_NE(&from, this);
  const PlanningConf* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PlanningConf>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:legion.planning.PlanningConf)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:legion.planning.PlanningConf)
    MergeFrom(*source);
  }
}

void PlanningConf::MergeFrom(const PlanningConf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:legion.planning.PlanningConf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_app_name(from._internal_app_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_description(from._internal_description());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_set_log_file_path(from._internal_log_file_path());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_mutable_messages()->::legion::common::Message::MergeFrom(from._internal_messages());
    }
    if (cached_has_bits & 0x00000010u) {
      _internal_mutable_lattice_planner_conf()->::legion::planning::LatticePlannerConf::MergeFrom(from._internal_lattice_planner_conf());
    }
    if (cached_has_bits & 0x00000020u) {
      _internal_mutable_parking_conf()->::legion::planning::ParkingConf::MergeFrom(from._internal_parking_conf());
    }
    if (cached_has_bits & 0x00000040u) {
      _internal_mutable_vehicle_param()->::legion::interface::VehicleParam::MergeFrom(from._internal_vehicle_param());
    }
    if (cached_has_bits & 0x00000080u) {
      _internal_mutable_status()->::legion::planning::StatusConfig::MergeFrom(from._internal_status());
    }
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      log_level_ = from.log_level_;
    }
    if (cached_has_bits & 0x00000200u) {
      logging_data_enable_ = from.logging_data_enable_;
    }
    if (cached_has_bits & 0x00000400u) {
      enable_log_debug_ = from.enable_log_debug_;
    }
    if (cached_has_bits & 0x00000800u) {
      use_system_timestamp_ = from.use_system_timestamp_;
    }
    if (cached_has_bits & 0x00001000u) {
      enable_local_map_topic_ = from.enable_local_map_topic_;
    }
    if (cached_has_bits & 0x00002000u) {
      produce_planning_command_duration_ = from.produce_planning_command_duration_;
    }
    if (cached_has_bits & 0x00004000u) {
      publish_planning_command_duration_ = from.publish_planning_command_duration_;
    }
    if (cached_has_bits & 0x00008000u) {
      min_speed_ = from.min_speed_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00ff0000u) {
    if (cached_has_bits & 0x00010000u) {
      threshold_static_speed_ = from.threshold_static_speed_;
    }
    if (cached_has_bits & 0x00020000u) {
      threshold_static_speed_self_ = from.threshold_static_speed_self_;
    }
    if (cached_has_bits & 0x00040000u) {
      path_density_ = from.path_density_;
    }
    if (cached_has_bits & 0x00080000u) {
      look_forward_time_sec_ = from.look_forward_time_sec_;
    }
    if (cached_has_bits & 0x00100000u) {
      look_forward_long_distance_ = from.look_forward_long_distance_;
    }
    if (cached_has_bits & 0x00200000u) {
      look_forward_short_distance_ = from.look_forward_short_distance_;
    }
    if (cached_has_bits & 0x00400000u) {
      look_backward_distance_ = from.look_backward_distance_;
    }
    if (cached_has_bits & 0x00800000u) {
      look_forward_extend_distance_ = from.look_forward_extend_distance_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0xff000000u) {
    if (cached_has_bits & 0x01000000u) {
      reference_line_stitch_overlap_distance_ = from.reference_line_stitch_overlap_distance_;
    }
    if (cached_has_bits & 0x02000000u) {
      enable_elevation_ = from.enable_elevation_;
    }
    if (cached_has_bits & 0x04000000u) {
      enable_lane_change_ = from.enable_lane_change_;
    }
    if (cached_has_bits & 0x08000000u) {
      enable_swerving_ = from.enable_swerving_;
    }
    if (cached_has_bits & 0x10000000u) {
      enable_following_ = from.enable_following_;
    }
    if (cached_has_bits & 0x20000000u) {
      enable_cutin_ = from.enable_cutin_;
    }
    if (cached_has_bits & 0x40000000u) {
      enable_traffic_light_behavior_ = from.enable_traffic_light_behavior_;
    }
    if (cached_has_bits & 0x80000000u) {
      enable_stop_sign_behavior_ = from.enable_stop_sign_behavior_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  cached_has_bits = from._has_bits_[1];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      enable_inward_outward_behavior_ = from.enable_inward_outward_behavior_;
    }
    if (cached_has_bits & 0x00000002u) {
      baselen_collison_check_ = from.baselen_collison_check_;
    }
    if (cached_has_bits & 0x00000004u) {
      speedcoeff_collision_check_ = from.speedcoeff_collision_check_;
    }
    if (cached_has_bits & 0x00000008u) {
      map_match_error_ = from.map_match_error_;
    }
    if (cached_has_bits & 0x00000010u) {
      lane_match_tolerance_ = from.lane_match_tolerance_;
    }
    if (cached_has_bits & 0x00000020u) {
      norm_acceleration_ = from.norm_acceleration_;
    }
    if (cached_has_bits & 0x00000040u) {
      norm_deceleration_ = from.norm_deceleration_;
    }
    if (cached_has_bits & 0x00000080u) {
      anchor_sampling_step_ = from.anchor_sampling_step_;
    }
    _has_bits_[1] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      knots_sampling_step_ = from.knots_sampling_step_;
    }
    if (cached_has_bits & 0x00000200u) {
      lateral_bound_limit_ = from.lateral_bound_limit_;
    }
    if (cached_has_bits & 0x00000400u) {
      safe_width_ = from.safe_width_;
    }
    if (cached_has_bits & 0x00000800u) {
      safe_length_ = from.safe_length_;
    }
    if (cached_has_bits & 0x00001000u) {
      safe_width_lower_limit_ = from.safe_width_lower_limit_;
    }
    if (cached_has_bits & 0x00002000u) {
      safe_length_lower_limit_ = from.safe_length_lower_limit_;
    }
    if (cached_has_bits & 0x00004000u) {
      safe_dis_speed_lower_limit_ = from.safe_dis_speed_lower_limit_;
    }
    if (cached_has_bits & 0x00008000u) {
      safe_dis_speed_upper_limit_ = from.safe_dis_speed_upper_limit_;
    }
    _has_bits_[1] |= cached_has_bits;
  }
  if (cached_has_bits & 0x003f0000u) {
    if (cached_has_bits & 0x00010000u) {
      emergency_time_interval_ = from.emergency_time_interval_;
    }
    if (cached_has_bits & 0x00020000u) {
      emergency_lower_limit_length_ = from.emergency_lower_limit_length_;
    }
    if (cached_has_bits & 0x00040000u) {
      decision_yield_distance_ = from.decision_yield_distance_;
    }
    if (cached_has_bits & 0x00080000u) {
      yield_offset_ = from.yield_offset_;
    }
    if (cached_has_bits & 0x00100000u) {
      virtual_length_max_ = from.virtual_length_max_;
    }
    if (cached_has_bits & 0x00200000u) {
      map_spline_order_ = from.map_spline_order_;
    }
    _has_bits_[1] |= cached_has_bits;
  }
}

void PlanningConf::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:legion.planning.PlanningConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlanningConf::CopyFrom(const PlanningConf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:legion.planning.PlanningConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlanningConf::IsInitialized() const {
  return true;
}

void PlanningConf::InternalSwap(PlanningConf* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(_has_bits_[1], other->_has_bits_[1]);
  app_name_.Swap(&other->app_name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  description_.Swap(&other->description_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  log_file_path_.Swap(&other->log_file_path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlanningConf, map_spline_order_)
      + sizeof(PlanningConf::map_spline_order_)
      - PROTOBUF_FIELD_OFFSET(PlanningConf, messages_)>(
          reinterpret_cast<char*>(&messages_),
          reinterpret_cast<char*>(&other->messages_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlanningConf::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class StatusConfig::_Internal {
 public:
  using HasBits = decltype(std::declval<StatusConfig>()._has_bits_);
  static void set_has_status_detect_duration(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

StatusConfig::StatusConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.planning.StatusConfig)
}
StatusConfig::StatusConfig(const StatusConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  status_detect_duration_ = from.status_detect_duration_;
  // @@protoc_insertion_point(copy_constructor:legion.planning.StatusConfig)
}

void StatusConfig::SharedCtor() {
  status_detect_duration_ = 0;
}

StatusConfig::~StatusConfig() {
  // @@protoc_insertion_point(destructor:legion.planning.StatusConfig)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void StatusConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void StatusConfig::ArenaDtor(void* object) {
  StatusConfig* _this = reinterpret_cast< StatusConfig* >(object);
  (void)_this;
}
void StatusConfig::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void StatusConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const StatusConfig& StatusConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_StatusConfig_modules_2fplanning_2fsrc_2fproto_2fplanning_5fconf_2eproto.base);
  return *internal_default_instance();
}


void StatusConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.planning.StatusConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_detect_duration_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StatusConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional double status_detect_duration = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          _Internal::set_has_status_detect_duration(&has_bits);
          status_detect_duration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* StatusConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:legion.planning.StatusConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double status_detect_duration = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_status_detect_duration(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.planning.StatusConfig)
  return target;
}

size_t StatusConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:legion.planning.StatusConfig)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional double status_detect_duration = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StatusConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:legion.planning.StatusConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const StatusConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<StatusConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:legion.planning.StatusConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:legion.planning.StatusConfig)
    MergeFrom(*source);
  }
}

void StatusConfig::MergeFrom(const StatusConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:legion.planning.StatusConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_status_detect_duration()) {
    _internal_set_status_detect_duration(from._internal_status_detect_duration());
  }
}

void StatusConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:legion.planning.StatusConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StatusConfig::CopyFrom(const StatusConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:legion.planning.StatusConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatusConfig::IsInitialized() const {
  return true;
}

void StatusConfig::InternalSwap(StatusConfig* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(status_detect_duration_, other->status_detect_duration_);
}

::PROTOBUF_NAMESPACE_ID::Metadata StatusConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace planning
}  // namespace legion
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::legion::planning::PlanningConf* Arena::CreateMaybeMessage< ::legion::planning::PlanningConf >(Arena* arena) {
  return Arena::CreateMessageInternal< ::legion::planning::PlanningConf >(arena);
}
template<> PROTOBUF_NOINLINE ::legion::planning::StatusConfig* Arena::CreateMaybeMessage< ::legion::planning::StatusConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::legion::planning::StatusConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
