// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/legion_bridge/src/proto/calibration_table.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto;
namespace legion {
namespace legion_bridge {
class CalibrationInfo;
class CalibrationInfoDefaultTypeInternal;
extern CalibrationInfoDefaultTypeInternal _CalibrationInfo_default_instance_;
class CalibrationTable;
class CalibrationTableDefaultTypeInternal;
extern CalibrationTableDefaultTypeInternal _CalibrationTable_default_instance_;
}  // namespace legion_bridge
}  // namespace legion
PROTOBUF_NAMESPACE_OPEN
template<> ::legion::legion_bridge::CalibrationInfo* Arena::CreateMaybeMessage<::legion::legion_bridge::CalibrationInfo>(Arena*);
template<> ::legion::legion_bridge::CalibrationTable* Arena::CreateMaybeMessage<::legion::legion_bridge::CalibrationTable>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace legion {
namespace legion_bridge {

// ===================================================================

class CalibrationTable PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:legion.legion_bridge.CalibrationTable) */ {
 public:
  inline CalibrationTable() : CalibrationTable(nullptr) {}
  virtual ~CalibrationTable();

  CalibrationTable(const CalibrationTable& from);
  CalibrationTable(CalibrationTable&& from) noexcept
    : CalibrationTable() {
    *this = ::std::move(from);
  }

  inline CalibrationTable& operator=(const CalibrationTable& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalibrationTable& operator=(CalibrationTable&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CalibrationTable& default_instance();

  static inline const CalibrationTable* internal_default_instance() {
    return reinterpret_cast<const CalibrationTable*>(
               &_CalibrationTable_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CalibrationTable& a, CalibrationTable& b) {
    a.Swap(&b);
  }
  inline void Swap(CalibrationTable* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalibrationTable* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CalibrationTable* New() const final {
    return CreateMaybeMessage<CalibrationTable>(nullptr);
  }

  CalibrationTable* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CalibrationTable>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CalibrationTable& from);
  void MergeFrom(const CalibrationTable& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CalibrationTable* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "legion.legion_bridge.CalibrationTable";
  }
  protected:
  explicit CalibrationTable(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto);
    return ::descriptor_table_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCalibrationTableFieldNumber = 1,
  };
  // repeated .legion.legion_bridge.CalibrationInfo calibration_table = 1;
  int calibration_table_size() const;
  private:
  int _internal_calibration_table_size() const;
  public:
  void clear_calibration_table();
  ::legion::legion_bridge::CalibrationInfo* mutable_calibration_table(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::legion::legion_bridge::CalibrationInfo >*
      mutable_calibration_table();
  private:
  const ::legion::legion_bridge::CalibrationInfo& _internal_calibration_table(int index) const;
  ::legion::legion_bridge::CalibrationInfo* _internal_add_calibration_table();
  public:
  const ::legion::legion_bridge::CalibrationInfo& calibration_table(int index) const;
  ::legion::legion_bridge::CalibrationInfo* add_calibration_table();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::legion::legion_bridge::CalibrationInfo >&
      calibration_table() const;

  // @@protoc_insertion_point(class_scope:legion.legion_bridge.CalibrationTable)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::legion::legion_bridge::CalibrationInfo > calibration_table_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto;
};
// -------------------------------------------------------------------

class CalibrationInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:legion.legion_bridge.CalibrationInfo) */ {
 public:
  inline CalibrationInfo() : CalibrationInfo(nullptr) {}
  virtual ~CalibrationInfo();

  CalibrationInfo(const CalibrationInfo& from);
  CalibrationInfo(CalibrationInfo&& from) noexcept
    : CalibrationInfo() {
    *this = ::std::move(from);
  }

  inline CalibrationInfo& operator=(const CalibrationInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CalibrationInfo& operator=(CalibrationInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CalibrationInfo& default_instance();

  static inline const CalibrationInfo* internal_default_instance() {
    return reinterpret_cast<const CalibrationInfo*>(
               &_CalibrationInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CalibrationInfo& a, CalibrationInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(CalibrationInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CalibrationInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CalibrationInfo* New() const final {
    return CreateMaybeMessage<CalibrationInfo>(nullptr);
  }

  CalibrationInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CalibrationInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CalibrationInfo& from);
  void MergeFrom(const CalibrationInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CalibrationInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "legion.legion_bridge.CalibrationInfo";
  }
  protected:
  explicit CalibrationInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto);
    return ::descriptor_table_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kBrakeFieldNumber = 2,
  };
  // optional double speed = 1;
  bool has_speed() const;
  private:
  bool _internal_has_speed() const;
  public:
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // optional double brake = 2;
  bool has_brake() const;
  private:
  bool _internal_has_brake() const;
  public:
  void clear_brake();
  double brake() const;
  void set_brake(double value);
  private:
  double _internal_brake() const;
  void _internal_set_brake(double value);
  public:

  // @@protoc_insertion_point(class_scope:legion.legion_bridge.CalibrationInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double speed_;
  double brake_;
  friend struct ::TableStruct_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CalibrationTable

// repeated .legion.legion_bridge.CalibrationInfo calibration_table = 1;
inline int CalibrationTable::_internal_calibration_table_size() const {
  return calibration_table_.size();
}
inline int CalibrationTable::calibration_table_size() const {
  return _internal_calibration_table_size();
}
inline void CalibrationTable::clear_calibration_table() {
  calibration_table_.Clear();
}
inline ::legion::legion_bridge::CalibrationInfo* CalibrationTable::mutable_calibration_table(int index) {
  // @@protoc_insertion_point(field_mutable:legion.legion_bridge.CalibrationTable.calibration_table)
  return calibration_table_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::legion::legion_bridge::CalibrationInfo >*
CalibrationTable::mutable_calibration_table() {
  // @@protoc_insertion_point(field_mutable_list:legion.legion_bridge.CalibrationTable.calibration_table)
  return &calibration_table_;
}
inline const ::legion::legion_bridge::CalibrationInfo& CalibrationTable::_internal_calibration_table(int index) const {
  return calibration_table_.Get(index);
}
inline const ::legion::legion_bridge::CalibrationInfo& CalibrationTable::calibration_table(int index) const {
  // @@protoc_insertion_point(field_get:legion.legion_bridge.CalibrationTable.calibration_table)
  return _internal_calibration_table(index);
}
inline ::legion::legion_bridge::CalibrationInfo* CalibrationTable::_internal_add_calibration_table() {
  return calibration_table_.Add();
}
inline ::legion::legion_bridge::CalibrationInfo* CalibrationTable::add_calibration_table() {
  // @@protoc_insertion_point(field_add:legion.legion_bridge.CalibrationTable.calibration_table)
  return _internal_add_calibration_table();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::legion::legion_bridge::CalibrationInfo >&
CalibrationTable::calibration_table() const {
  // @@protoc_insertion_point(field_list:legion.legion_bridge.CalibrationTable.calibration_table)
  return calibration_table_;
}

// -------------------------------------------------------------------

// CalibrationInfo

// optional double speed = 1;
inline bool CalibrationInfo::_internal_has_speed() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CalibrationInfo::has_speed() const {
  return _internal_has_speed();
}
inline void CalibrationInfo::clear_speed() {
  speed_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double CalibrationInfo::_internal_speed() const {
  return speed_;
}
inline double CalibrationInfo::speed() const {
  // @@protoc_insertion_point(field_get:legion.legion_bridge.CalibrationInfo.speed)
  return _internal_speed();
}
inline void CalibrationInfo::_internal_set_speed(double value) {
  _has_bits_[0] |= 0x00000001u;
  speed_ = value;
}
inline void CalibrationInfo::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:legion.legion_bridge.CalibrationInfo.speed)
}

// optional double brake = 2;
inline bool CalibrationInfo::_internal_has_brake() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CalibrationInfo::has_brake() const {
  return _internal_has_brake();
}
inline void CalibrationInfo::clear_brake() {
  brake_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double CalibrationInfo::_internal_brake() const {
  return brake_;
}
inline double CalibrationInfo::brake() const {
  // @@protoc_insertion_point(field_get:legion.legion_bridge.CalibrationInfo.brake)
  return _internal_brake();
}
inline void CalibrationInfo::_internal_set_brake(double value) {
  _has_bits_[0] |= 0x00000002u;
  brake_ = value;
}
inline void CalibrationInfo::set_brake(double value) {
  _internal_set_brake(value);
  // @@protoc_insertion_point(field_set:legion.legion_bridge.CalibrationInfo.brake)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace legion_bridge
}  // namespace legion

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2flegion_5fbridge_2fsrc_2fproto_2fcalibration_5ftable_2eproto
