 #ifndef __Vehicle__idl__
#define __Vehicle__idl__
#include "Header.idl"
module ros2_interface{
 module msg{
  struct Vehicle{
    ros2_interface::msg::Header   _header;
    int32   _vehicle_type;
    string   _vid;
    string   _vehicle_num;
    string   _oid;
    int32   _operation;
    double   _totalcurrent;
    double   _batterysoc;
    double   _totalvoltage;
    double   _recharge;
    int32   _dcdc;
    uint32   _resistance;
    sequence<uint8> _seats;
    int32   _servicemode;
    sequence<int32> _seat_belt;
    int32   _engine_status;
    double   _battery_voltage;
    double   _battery_ammeter;
    double   _battery_consumption;
    double   _battery_probe;
    sequence<double> _battery_temperatures;
    double   _battery_h_tepemperatures;
    double   _battery_ltepemperatures;
    double   _battery_probe_code;
    double   _battery_h_concentration;
    double   _battery_c_sensor_code;
    double   _battery_stress;
    double   _battery_s_sensor_code;
    double   _battery_h_dc_dc;
    double   _battery_capacity;
    double   _airconditioning_idx;
    double   _airconditioning_status;
    int32   _airconditioning_model;
    int32   _airconditioning_volume;
    int32   _airconditioning_defrost;
    sequence<int32> _door_status;
    double   _rsrp;
    double   _sinr;
    double   _uspeed;
    double   _dspeed;
    double   _loss;
    uint32   _delay;
    uint8   _refrigeration_idx;
    int32   _refrigeration_status;
    double   _refrigeration_stemp;
    double   _refrigeration_ctemp;
    uint8   _driving_motor_idx;
    uint8   _driving_motor_status;
    double   _driving_motor_ctemp;
    uint8   _driving_motor_rspeed;
    double   _driving_motor_torque;
    double   _driving_motor_etemp;
    double   _driving_motor_voltage;
    double   _driving_motor_ammeter;
    int32   _outline_lamp_status;
    int32   _warning_lamp_status;
    int32   _backlight_lamp_status;
    int32   _brakelamp_lamp_status;
    int32   _left_lamp_status;
    int32   _right_lamp_status;
    int32   _front_touch_status;
    int32   _rear_touch_status;
    int32   _horn_status;
    int8   _length;
    int8   _width;
    int8   _height;
    int32   _cleanup_switch_status;
    int32   _watering_switch_status;
    int32   _trash_can_status;
    int32   _water_tank_status;
    int32   _water_add_switch_status;
    int32   _hatch_unlock_switch_status;
    double   _water_tank_level;
    int32   _hmi_highbeam;
    int32   _hmi_cleanup;
    int32   _hmi_watering;
    int32   _bms_charge_status;
    int32   _emergency_button_status;
    int32   _traction;
    int32   _abs;
    int32   _scs;
    int32   _brake_boost;
    int32   _aux_brakes;
  };
 };
}; 
#endif