// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/control/src/proto/lqr_calibration_table.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto;
class LqrCalibrationTable;
class LqrCalibrationTableDefaultTypeInternal;
extern LqrCalibrationTableDefaultTypeInternal _LqrCalibrationTable_default_instance_;
class LqrCalibrationTableInfo;
class LqrCalibrationTableInfoDefaultTypeInternal;
extern LqrCalibrationTableInfoDefaultTypeInternal _LqrCalibrationTableInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::LqrCalibrationTable* Arena::CreateMaybeMessage<::LqrCalibrationTable>(Arena*);
template<> ::LqrCalibrationTableInfo* Arena::CreateMaybeMessage<::LqrCalibrationTableInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class LqrCalibrationTableInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LqrCalibrationTableInfo) */ {
 public:
  inline LqrCalibrationTableInfo() : LqrCalibrationTableInfo(nullptr) {}
  virtual ~LqrCalibrationTableInfo();

  LqrCalibrationTableInfo(const LqrCalibrationTableInfo& from);
  LqrCalibrationTableInfo(LqrCalibrationTableInfo&& from) noexcept
    : LqrCalibrationTableInfo() {
    *this = ::std::move(from);
  }

  inline LqrCalibrationTableInfo& operator=(const LqrCalibrationTableInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline LqrCalibrationTableInfo& operator=(LqrCalibrationTableInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LqrCalibrationTableInfo& default_instance();

  static inline const LqrCalibrationTableInfo* internal_default_instance() {
    return reinterpret_cast<const LqrCalibrationTableInfo*>(
               &_LqrCalibrationTableInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LqrCalibrationTableInfo& a, LqrCalibrationTableInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(LqrCalibrationTableInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LqrCalibrationTableInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LqrCalibrationTableInfo* New() const final {
    return CreateMaybeMessage<LqrCalibrationTableInfo>(nullptr);
  }

  LqrCalibrationTableInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LqrCalibrationTableInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LqrCalibrationTableInfo& from);
  void MergeFrom(const LqrCalibrationTableInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LqrCalibrationTableInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LqrCalibrationTableInfo";
  }
  protected:
  explicit LqrCalibrationTableInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto);
    return ::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKFieldNumber = 2,
    kVFieldNumber = 1,
  };
  // repeated double k = 2;
  int k_size() const;
  private:
  int _internal_k_size() const;
  public:
  void clear_k();
  private:
  double _internal_k(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_k() const;
  void _internal_add_k(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_k();
  public:
  double k(int index) const;
  void set_k(int index, double value);
  void add_k(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      k() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_k();

  // optional double v = 1;
  bool has_v() const;
  private:
  bool _internal_has_v() const;
  public:
  void clear_v();
  double v() const;
  void set_v(double value);
  private:
  double _internal_v() const;
  void _internal_set_v(double value);
  public:

  // @@protoc_insertion_point(class_scope:LqrCalibrationTableInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > k_;
  double v_;
  friend struct ::TableStruct_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto;
};
// -------------------------------------------------------------------

class LqrCalibrationTable PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LqrCalibrationTable) */ {
 public:
  inline LqrCalibrationTable() : LqrCalibrationTable(nullptr) {}
  virtual ~LqrCalibrationTable();

  LqrCalibrationTable(const LqrCalibrationTable& from);
  LqrCalibrationTable(LqrCalibrationTable&& from) noexcept
    : LqrCalibrationTable() {
    *this = ::std::move(from);
  }

  inline LqrCalibrationTable& operator=(const LqrCalibrationTable& from) {
    CopyFrom(from);
    return *this;
  }
  inline LqrCalibrationTable& operator=(LqrCalibrationTable&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LqrCalibrationTable& default_instance();

  static inline const LqrCalibrationTable* internal_default_instance() {
    return reinterpret_cast<const LqrCalibrationTable*>(
               &_LqrCalibrationTable_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LqrCalibrationTable& a, LqrCalibrationTable& b) {
    a.Swap(&b);
  }
  inline void Swap(LqrCalibrationTable* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LqrCalibrationTable* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LqrCalibrationTable* New() const final {
    return CreateMaybeMessage<LqrCalibrationTable>(nullptr);
  }

  LqrCalibrationTable* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LqrCalibrationTable>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LqrCalibrationTable& from);
  void MergeFrom(const LqrCalibrationTable& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LqrCalibrationTable* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LqrCalibrationTable";
  }
  protected:
  explicit LqrCalibrationTable(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto);
    return ::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCalibrationTableFieldNumber = 1,
  };
  // repeated .LqrCalibrationTableInfo calibration_table = 1;
  int calibration_table_size() const;
  private:
  int _internal_calibration_table_size() const;
  public:
  void clear_calibration_table();
  ::LqrCalibrationTableInfo* mutable_calibration_table(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LqrCalibrationTableInfo >*
      mutable_calibration_table();
  private:
  const ::LqrCalibrationTableInfo& _internal_calibration_table(int index) const;
  ::LqrCalibrationTableInfo* _internal_add_calibration_table();
  public:
  const ::LqrCalibrationTableInfo& calibration_table(int index) const;
  ::LqrCalibrationTableInfo* add_calibration_table();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LqrCalibrationTableInfo >&
      calibration_table() const;

  // @@protoc_insertion_point(class_scope:LqrCalibrationTable)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LqrCalibrationTableInfo > calibration_table_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LqrCalibrationTableInfo

// optional double v = 1;
inline bool LqrCalibrationTableInfo::_internal_has_v() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LqrCalibrationTableInfo::has_v() const {
  return _internal_has_v();
}
inline void LqrCalibrationTableInfo::clear_v() {
  v_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double LqrCalibrationTableInfo::_internal_v() const {
  return v_;
}
inline double LqrCalibrationTableInfo::v() const {
  // @@protoc_insertion_point(field_get:LqrCalibrationTableInfo.v)
  return _internal_v();
}
inline void LqrCalibrationTableInfo::_internal_set_v(double value) {
  _has_bits_[0] |= 0x00000001u;
  v_ = value;
}
inline void LqrCalibrationTableInfo::set_v(double value) {
  _internal_set_v(value);
  // @@protoc_insertion_point(field_set:LqrCalibrationTableInfo.v)
}

// repeated double k = 2;
inline int LqrCalibrationTableInfo::_internal_k_size() const {
  return k_.size();
}
inline int LqrCalibrationTableInfo::k_size() const {
  return _internal_k_size();
}
inline void LqrCalibrationTableInfo::clear_k() {
  k_.Clear();
}
inline double LqrCalibrationTableInfo::_internal_k(int index) const {
  return k_.Get(index);
}
inline double LqrCalibrationTableInfo::k(int index) const {
  // @@protoc_insertion_point(field_get:LqrCalibrationTableInfo.k)
  return _internal_k(index);
}
inline void LqrCalibrationTableInfo::set_k(int index, double value) {
  k_.Set(index, value);
  // @@protoc_insertion_point(field_set:LqrCalibrationTableInfo.k)
}
inline void LqrCalibrationTableInfo::_internal_add_k(double value) {
  k_.Add(value);
}
inline void LqrCalibrationTableInfo::add_k(double value) {
  _internal_add_k(value);
  // @@protoc_insertion_point(field_add:LqrCalibrationTableInfo.k)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
LqrCalibrationTableInfo::_internal_k() const {
  return k_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
LqrCalibrationTableInfo::k() const {
  // @@protoc_insertion_point(field_list:LqrCalibrationTableInfo.k)
  return _internal_k();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
LqrCalibrationTableInfo::_internal_mutable_k() {
  return &k_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
LqrCalibrationTableInfo::mutable_k() {
  // @@protoc_insertion_point(field_mutable_list:LqrCalibrationTableInfo.k)
  return _internal_mutable_k();
}

// -------------------------------------------------------------------

// LqrCalibrationTable

// repeated .LqrCalibrationTableInfo calibration_table = 1;
inline int LqrCalibrationTable::_internal_calibration_table_size() const {
  return calibration_table_.size();
}
inline int LqrCalibrationTable::calibration_table_size() const {
  return _internal_calibration_table_size();
}
inline void LqrCalibrationTable::clear_calibration_table() {
  calibration_table_.Clear();
}
inline ::LqrCalibrationTableInfo* LqrCalibrationTable::mutable_calibration_table(int index) {
  // @@protoc_insertion_point(field_mutable:LqrCalibrationTable.calibration_table)
  return calibration_table_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LqrCalibrationTableInfo >*
LqrCalibrationTable::mutable_calibration_table() {
  // @@protoc_insertion_point(field_mutable_list:LqrCalibrationTable.calibration_table)
  return &calibration_table_;
}
inline const ::LqrCalibrationTableInfo& LqrCalibrationTable::_internal_calibration_table(int index) const {
  return calibration_table_.Get(index);
}
inline const ::LqrCalibrationTableInfo& LqrCalibrationTable::calibration_table(int index) const {
  // @@protoc_insertion_point(field_get:LqrCalibrationTable.calibration_table)
  return _internal_calibration_table(index);
}
inline ::LqrCalibrationTableInfo* LqrCalibrationTable::_internal_add_calibration_table() {
  return calibration_table_.Add();
}
inline ::LqrCalibrationTableInfo* LqrCalibrationTable::add_calibration_table() {
  // @@protoc_insertion_point(field_add:LqrCalibrationTable.calibration_table)
  return _internal_add_calibration_table();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::LqrCalibrationTableInfo >&
LqrCalibrationTable::calibration_table() const {
  // @@protoc_insertion_point(field_list:LqrCalibrationTable.calibration_table)
  return calibration_table_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2fcontrol_2fsrc_2fproto_2flqr_5fcalibration_5ftable_2eproto
