// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/control/src/proto/purepursuit_controller_conf.proto

#include "modules/control/src/proto/purepursuit_controller_conf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_modules_2fcontrol_2fsrc_2fproto_2fpid_5fconf_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PIDConf_modules_2fcontrol_2fsrc_2fproto_2fpid_5fconf_2eproto;
namespace legion {
namespace control {
class PurePursuitControllerConfDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PurePursuitControllerConf> _instance;
} _PurePursuitControllerConf_default_instance_;
}  // namespace control
}  // namespace legion
static void InitDefaultsscc_info_PurePursuitControllerConf_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::legion::control::_PurePursuitControllerConf_default_instance_;
    new (ptr) ::legion::control::PurePursuitControllerConf();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PurePursuitControllerConf_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PurePursuitControllerConf_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto}, {
      &scc_info_PIDConf_modules_2fcontrol_2fsrc_2fproto_2fpid_5fconf_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, use_delay_compensation_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, use_interpolate_lookahead_point_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, minimum_lookahead_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, maximum_lookahead_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, speed_to_lookahead_ratio_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, enable_log_debug_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, max_lateral_acceleration_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, ts_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, lookahead_station_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, lookback_station_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, enable_digital_filter_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, cutoff_freq_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, enable_heading_error_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, heading_error_pid_conf_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, enable_lat_error_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, lat_error_pid_conf_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, heading_error_gain_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, lat_error_gain_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, lat_error_threshold_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, heading_error_threshold_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, purepursuit_minimum_lookahead_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, purepursuit_maximum_lookahead_distance_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, purepursuit_speed_to_lookahead_ratio_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, lat_error_min_threshold_),
  PROTOBUF_FIELD_OFFSET(::legion::control::PurePursuitControllerConf, heading_error_min_threshold_),
  7,
  8,
  2,
  3,
  4,
  9,
  5,
  6,
  13,
  14,
  10,
  15,
  11,
  0,
  12,
  1,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 30, sizeof(::legion::control::PurePursuitControllerConf)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::legion::control::_PurePursuitControllerConf_default_instance_),
};

const char descriptor_table_protodef_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n;modules/control/src/proto/purepursuit_"
  "controller_conf.proto\022\016legion.control\032(m"
  "odules/control/src/proto/pid_conf.proto\""
  "\353\006\n\031PurePursuitControllerConf\022\036\n\026use_del"
  "ay_compensation\030\001 \001(\010\022\'\n\037use_interpolate"
  "_lookahead_point\030\002 \001(\010\022\"\n\032minimum_lookah"
  "ead_distance\030\003 \001(\001\022\"\n\032maximum_lookahead_"
  "distance\030\004 \001(\001\022 \n\030speed_to_lookahead_rat"
  "io\030\005 \001(\001\022\030\n\020enable_log_debug\030\006 \001(\010\022 \n\030ma"
  "x_lateral_acceleration\030\007 \001(\001\022\n\n\002ts\030\010 \001(\001"
  "\022\031\n\021lookahead_station\030\t \001(\001\022\030\n\020lookback_"
  "station\030\n \001(\001\022\035\n\025enable_digital_filter\030\013"
  " \001(\010\022\023\n\013cutoff_freq\030\014 \001(\001\022\034\n\024enable_head"
  "ing_error\030\r \001(\010\0227\n\026heading_error_pid_con"
  "f\030\016 \001(\0132\027.legion.control.PIDConf\022\030\n\020enab"
  "le_lat_error\030\017 \001(\010\0223\n\022lat_error_pid_conf"
  "\030\020 \001(\0132\027.legion.control.PIDConf\022\032\n\022headi"
  "ng_error_gain\030\021 \001(\001\022\026\n\016lat_error_gain\030\022 "
  "\001(\001\022\033\n\023lat_error_threshold\030\023 \001(\001\022\037\n\027head"
  "ing_error_threshold\030\024 \001(\001\022.\n&purepursuit"
  "_minimum_lookahead_distance\030\025 \001(\001\022.\n&pur"
  "epursuit_maximum_lookahead_distance\030\026 \001("
  "\001\022,\n$purepursuit_speed_to_lookahead_rati"
  "o\030\027 \001(\001\022\037\n\027lat_error_min_threshold\030\030 \001(\001"
  "\022#\n\033heading_error_min_threshold\030\031 \001(\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto_deps[1] = {
  &::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpid_5fconf_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto_sccs[1] = {
  &scc_info_PurePursuitControllerConf_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto = {
  false, false, descriptor_table_protodef_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto, "modules/control/src/proto/purepursuit_controller_conf.proto", 997,
  &descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto_once, descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto_sccs, descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto::offsets,
  file_level_metadata_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto, 1, file_level_enum_descriptors_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto, file_level_service_descriptors_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto)), true);
namespace legion {
namespace control {

// ===================================================================

class PurePursuitControllerConf::_Internal {
 public:
  using HasBits = decltype(std::declval<PurePursuitControllerConf>()._has_bits_);
  static void set_has_use_delay_compensation(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_use_interpolate_lookahead_point(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_minimum_lookahead_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_maximum_lookahead_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_speed_to_lookahead_ratio(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_enable_log_debug(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_max_lateral_acceleration(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_ts(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_lookahead_station(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_lookback_station(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static void set_has_enable_digital_filter(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_cutoff_freq(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
  static void set_has_enable_heading_error(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static const ::legion::control::PIDConf& heading_error_pid_conf(const PurePursuitControllerConf* msg);
  static void set_has_heading_error_pid_conf(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_enable_lat_error(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static const ::legion::control::PIDConf& lat_error_pid_conf(const PurePursuitControllerConf* msg);
  static void set_has_lat_error_pid_conf(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_heading_error_gain(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static void set_has_lat_error_gain(HasBits* has_bits) {
    (*has_bits)[0] |= 131072u;
  }
  static void set_has_lat_error_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 262144u;
  }
  static void set_has_heading_error_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 524288u;
  }
  static void set_has_purepursuit_minimum_lookahead_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 1048576u;
  }
  static void set_has_purepursuit_maximum_lookahead_distance(HasBits* has_bits) {
    (*has_bits)[0] |= 2097152u;
  }
  static void set_has_purepursuit_speed_to_lookahead_ratio(HasBits* has_bits) {
    (*has_bits)[0] |= 4194304u;
  }
  static void set_has_lat_error_min_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 8388608u;
  }
  static void set_has_heading_error_min_threshold(HasBits* has_bits) {
    (*has_bits)[0] |= 16777216u;
  }
};

const ::legion::control::PIDConf&
PurePursuitControllerConf::_Internal::heading_error_pid_conf(const PurePursuitControllerConf* msg) {
  return *msg->heading_error_pid_conf_;
}
const ::legion::control::PIDConf&
PurePursuitControllerConf::_Internal::lat_error_pid_conf(const PurePursuitControllerConf* msg) {
  return *msg->lat_error_pid_conf_;
}
void PurePursuitControllerConf::clear_heading_error_pid_conf() {
  if (heading_error_pid_conf_ != nullptr) heading_error_pid_conf_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void PurePursuitControllerConf::clear_lat_error_pid_conf() {
  if (lat_error_pid_conf_ != nullptr) lat_error_pid_conf_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
PurePursuitControllerConf::PurePursuitControllerConf(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:legion.control.PurePursuitControllerConf)
}
PurePursuitControllerConf::PurePursuitControllerConf(const PurePursuitControllerConf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_heading_error_pid_conf()) {
    heading_error_pid_conf_ = new ::legion::control::PIDConf(*from.heading_error_pid_conf_);
  } else {
    heading_error_pid_conf_ = nullptr;
  }
  if (from._internal_has_lat_error_pid_conf()) {
    lat_error_pid_conf_ = new ::legion::control::PIDConf(*from.lat_error_pid_conf_);
  } else {
    lat_error_pid_conf_ = nullptr;
  }
  ::memcpy(&minimum_lookahead_distance_, &from.minimum_lookahead_distance_,
    static_cast<size_t>(reinterpret_cast<char*>(&heading_error_min_threshold_) -
    reinterpret_cast<char*>(&minimum_lookahead_distance_)) + sizeof(heading_error_min_threshold_));
  // @@protoc_insertion_point(copy_constructor:legion.control.PurePursuitControllerConf)
}

void PurePursuitControllerConf::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PurePursuitControllerConf_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&heading_error_pid_conf_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&heading_error_min_threshold_) -
      reinterpret_cast<char*>(&heading_error_pid_conf_)) + sizeof(heading_error_min_threshold_));
}

PurePursuitControllerConf::~PurePursuitControllerConf() {
  // @@protoc_insertion_point(destructor:legion.control.PurePursuitControllerConf)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PurePursuitControllerConf::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete heading_error_pid_conf_;
  if (this != internal_default_instance()) delete lat_error_pid_conf_;
}

void PurePursuitControllerConf::ArenaDtor(void* object) {
  PurePursuitControllerConf* _this = reinterpret_cast< PurePursuitControllerConf* >(object);
  (void)_this;
}
void PurePursuitControllerConf::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PurePursuitControllerConf::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PurePursuitControllerConf& PurePursuitControllerConf::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PurePursuitControllerConf_modules_2fcontrol_2fsrc_2fproto_2fpurepursuit_5fcontroller_5fconf_2eproto.base);
  return *internal_default_instance();
}


void PurePursuitControllerConf::Clear() {
// @@protoc_insertion_point(message_clear_start:legion.control.PurePursuitControllerConf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(heading_error_pid_conf_ != nullptr);
      heading_error_pid_conf_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(lat_error_pid_conf_ != nullptr);
      lat_error_pid_conf_->Clear();
    }
  }
  if (cached_has_bits & 0x000000fcu) {
    ::memset(&minimum_lookahead_distance_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&use_delay_compensation_) -
        reinterpret_cast<char*>(&minimum_lookahead_distance_)) + sizeof(use_delay_compensation_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&use_interpolate_lookahead_point_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&cutoff_freq_) -
        reinterpret_cast<char*>(&use_interpolate_lookahead_point_)) + sizeof(cutoff_freq_));
  }
  if (cached_has_bits & 0x00ff0000u) {
    ::memset(&heading_error_gain_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&lat_error_min_threshold_) -
        reinterpret_cast<char*>(&heading_error_gain_)) + sizeof(lat_error_min_threshold_));
  }
  heading_error_min_threshold_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PurePursuitControllerConf::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional bool use_delay_compensation = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_use_delay_compensation(&has_bits);
          use_delay_compensation_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool use_interpolate_lookahead_point = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_use_interpolate_lookahead_point(&has_bits);
          use_interpolate_lookahead_point_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double minimum_lookahead_distance = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          _Internal::set_has_minimum_lookahead_distance(&has_bits);
          minimum_lookahead_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double maximum_lookahead_distance = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 33)) {
          _Internal::set_has_maximum_lookahead_distance(&has_bits);
          maximum_lookahead_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double speed_to_lookahead_ratio = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          _Internal::set_has_speed_to_lookahead_ratio(&has_bits);
          speed_to_lookahead_ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional bool enable_log_debug = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_enable_log_debug(&has_bits);
          enable_log_debug_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double max_lateral_acceleration = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 57)) {
          _Internal::set_has_max_lateral_acceleration(&has_bits);
          max_lateral_acceleration_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double ts = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 65)) {
          _Internal::set_has_ts(&has_bits);
          ts_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lookahead_station = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 73)) {
          _Internal::set_has_lookahead_station(&has_bits);
          lookahead_station_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lookback_station = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 81)) {
          _Internal::set_has_lookback_station(&has_bits);
          lookback_station_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional bool enable_digital_filter = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          _Internal::set_has_enable_digital_filter(&has_bits);
          enable_digital_filter_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double cutoff_freq = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 97)) {
          _Internal::set_has_cutoff_freq(&has_bits);
          cutoff_freq_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional bool enable_heading_error = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 104)) {
          _Internal::set_has_enable_heading_error(&has_bits);
          enable_heading_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .legion.control.PIDConf heading_error_pid_conf = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ctx->ParseMessage(_internal_mutable_heading_error_pid_conf(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool enable_lat_error = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          _Internal::set_has_enable_lat_error(&has_bits);
          enable_lat_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .legion.control.PIDConf lat_error_pid_conf = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          ptr = ctx->ParseMessage(_internal_mutable_lat_error_pid_conf(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional double heading_error_gain = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 137)) {
          _Internal::set_has_heading_error_gain(&has_bits);
          heading_error_gain_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lat_error_gain = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 145)) {
          _Internal::set_has_lat_error_gain(&has_bits);
          lat_error_gain_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lat_error_threshold = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 153)) {
          _Internal::set_has_lat_error_threshold(&has_bits);
          lat_error_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double heading_error_threshold = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 161)) {
          _Internal::set_has_heading_error_threshold(&has_bits);
          heading_error_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double purepursuit_minimum_lookahead_distance = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 169)) {
          _Internal::set_has_purepursuit_minimum_lookahead_distance(&has_bits);
          purepursuit_minimum_lookahead_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double purepursuit_maximum_lookahead_distance = 22;
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 177)) {
          _Internal::set_has_purepursuit_maximum_lookahead_distance(&has_bits);
          purepursuit_maximum_lookahead_distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double purepursuit_speed_to_lookahead_ratio = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 185)) {
          _Internal::set_has_purepursuit_speed_to_lookahead_ratio(&has_bits);
          purepursuit_speed_to_lookahead_ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double lat_error_min_threshold = 24;
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 193)) {
          _Internal::set_has_lat_error_min_threshold(&has_bits);
          lat_error_min_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // optional double heading_error_min_threshold = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 201)) {
          _Internal::set_has_heading_error_min_threshold(&has_bits);
          heading_error_min_threshold_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PurePursuitControllerConf::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:legion.control.PurePursuitControllerConf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool use_delay_compensation = 1;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_use_delay_compensation(), target);
  }

  // optional bool use_interpolate_lookahead_point = 2;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_use_interpolate_lookahead_point(), target);
  }

  // optional double minimum_lookahead_distance = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_minimum_lookahead_distance(), target);
  }

  // optional double maximum_lookahead_distance = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_maximum_lookahead_distance(), target);
  }

  // optional double speed_to_lookahead_ratio = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_speed_to_lookahead_ratio(), target);
  }

  // optional bool enable_log_debug = 6;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_enable_log_debug(), target);
  }

  // optional double max_lateral_acceleration = 7;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(7, this->_internal_max_lateral_acceleration(), target);
  }

  // optional double ts = 8;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(8, this->_internal_ts(), target);
  }

  // optional double lookahead_station = 9;
  if (cached_has_bits & 0x00002000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(9, this->_internal_lookahead_station(), target);
  }

  // optional double lookback_station = 10;
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(10, this->_internal_lookback_station(), target);
  }

  // optional bool enable_digital_filter = 11;
  if (cached_has_bits & 0x00000400u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(11, this->_internal_enable_digital_filter(), target);
  }

  // optional double cutoff_freq = 12;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(12, this->_internal_cutoff_freq(), target);
  }

  // optional bool enable_heading_error = 13;
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(13, this->_internal_enable_heading_error(), target);
  }

  // optional .legion.control.PIDConf heading_error_pid_conf = 14;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        14, _Internal::heading_error_pid_conf(this), target, stream);
  }

  // optional bool enable_lat_error = 15;
  if (cached_has_bits & 0x00001000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(15, this->_internal_enable_lat_error(), target);
  }

  // optional .legion.control.PIDConf lat_error_pid_conf = 16;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        16, _Internal::lat_error_pid_conf(this), target, stream);
  }

  // optional double heading_error_gain = 17;
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(17, this->_internal_heading_error_gain(), target);
  }

  // optional double lat_error_gain = 18;
  if (cached_has_bits & 0x00020000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(18, this->_internal_lat_error_gain(), target);
  }

  // optional double lat_error_threshold = 19;
  if (cached_has_bits & 0x00040000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(19, this->_internal_lat_error_threshold(), target);
  }

  // optional double heading_error_threshold = 20;
  if (cached_has_bits & 0x00080000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(20, this->_internal_heading_error_threshold(), target);
  }

  // optional double purepursuit_minimum_lookahead_distance = 21;
  if (cached_has_bits & 0x00100000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(21, this->_internal_purepursuit_minimum_lookahead_distance(), target);
  }

  // optional double purepursuit_maximum_lookahead_distance = 22;
  if (cached_has_bits & 0x00200000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(22, this->_internal_purepursuit_maximum_lookahead_distance(), target);
  }

  // optional double purepursuit_speed_to_lookahead_ratio = 23;
  if (cached_has_bits & 0x00400000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(23, this->_internal_purepursuit_speed_to_lookahead_ratio(), target);
  }

  // optional double lat_error_min_threshold = 24;
  if (cached_has_bits & 0x00800000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(24, this->_internal_lat_error_min_threshold(), target);
  }

  // optional double heading_error_min_threshold = 25;
  if (cached_has_bits & 0x01000000u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(25, this->_internal_heading_error_min_threshold(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legion.control.PurePursuitControllerConf)
  return target;
}

size_t PurePursuitControllerConf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:legion.control.PurePursuitControllerConf)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional .legion.control.PIDConf heading_error_pid_conf = 14;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *heading_error_pid_conf_);
    }

    // optional .legion.control.PIDConf lat_error_pid_conf = 16;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *lat_error_pid_conf_);
    }

    // optional double minimum_lookahead_distance = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 8;
    }

    // optional double maximum_lookahead_distance = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double speed_to_lookahead_ratio = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional double max_lateral_acceleration = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

    // optional double ts = 8;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 8;
    }

    // optional bool use_delay_compensation = 1;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 1;
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional bool use_interpolate_lookahead_point = 2;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + 1;
    }

    // optional bool enable_log_debug = 6;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 + 1;
    }

    // optional bool enable_digital_filter = 11;
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 + 1;
    }

    // optional bool enable_heading_error = 13;
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 + 1;
    }

    // optional bool enable_lat_error = 15;
    if (cached_has_bits & 0x00001000u) {
      total_size += 1 + 1;
    }

    // optional double lookahead_station = 9;
    if (cached_has_bits & 0x00002000u) {
      total_size += 1 + 8;
    }

    // optional double lookback_station = 10;
    if (cached_has_bits & 0x00004000u) {
      total_size += 1 + 8;
    }

    // optional double cutoff_freq = 12;
    if (cached_has_bits & 0x00008000u) {
      total_size += 1 + 8;
    }

  }
  if (cached_has_bits & 0x00ff0000u) {
    // optional double heading_error_gain = 17;
    if (cached_has_bits & 0x00010000u) {
      total_size += 2 + 8;
    }

    // optional double lat_error_gain = 18;
    if (cached_has_bits & 0x00020000u) {
      total_size += 2 + 8;
    }

    // optional double lat_error_threshold = 19;
    if (cached_has_bits & 0x00040000u) {
      total_size += 2 + 8;
    }

    // optional double heading_error_threshold = 20;
    if (cached_has_bits & 0x00080000u) {
      total_size += 2 + 8;
    }

    // optional double purepursuit_minimum_lookahead_distance = 21;
    if (cached_has_bits & 0x00100000u) {
      total_size += 2 + 8;
    }

    // optional double purepursuit_maximum_lookahead_distance = 22;
    if (cached_has_bits & 0x00200000u) {
      total_size += 2 + 8;
    }

    // optional double purepursuit_speed_to_lookahead_ratio = 23;
    if (cached_has_bits & 0x00400000u) {
      total_size += 2 + 8;
    }

    // optional double lat_error_min_threshold = 24;
    if (cached_has_bits & 0x00800000u) {
      total_size += 2 + 8;
    }

  }
  // optional double heading_error_min_threshold = 25;
  if (cached_has_bits & 0x01000000u) {
    total_size += 2 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PurePursuitControllerConf::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:legion.control.PurePursuitControllerConf)
  GOOGLE_DCHECK_NE(&from, this);
  const PurePursuitControllerConf* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PurePursuitControllerConf>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:legion.control.PurePursuitControllerConf)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:legion.control.PurePursuitControllerConf)
    MergeFrom(*source);
  }
}

void PurePursuitControllerConf::MergeFrom(const PurePursuitControllerConf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:legion.control.PurePursuitControllerConf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_heading_error_pid_conf()->::legion::control::PIDConf::MergeFrom(from._internal_heading_error_pid_conf());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_lat_error_pid_conf()->::legion::control::PIDConf::MergeFrom(from._internal_lat_error_pid_conf());
    }
    if (cached_has_bits & 0x00000004u) {
      minimum_lookahead_distance_ = from.minimum_lookahead_distance_;
    }
    if (cached_has_bits & 0x00000008u) {
      maximum_lookahead_distance_ = from.maximum_lookahead_distance_;
    }
    if (cached_has_bits & 0x00000010u) {
      speed_to_lookahead_ratio_ = from.speed_to_lookahead_ratio_;
    }
    if (cached_has_bits & 0x00000020u) {
      max_lateral_acceleration_ = from.max_lateral_acceleration_;
    }
    if (cached_has_bits & 0x00000040u) {
      ts_ = from.ts_;
    }
    if (cached_has_bits & 0x00000080u) {
      use_delay_compensation_ = from.use_delay_compensation_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      use_interpolate_lookahead_point_ = from.use_interpolate_lookahead_point_;
    }
    if (cached_has_bits & 0x00000200u) {
      enable_log_debug_ = from.enable_log_debug_;
    }
    if (cached_has_bits & 0x00000400u) {
      enable_digital_filter_ = from.enable_digital_filter_;
    }
    if (cached_has_bits & 0x00000800u) {
      enable_heading_error_ = from.enable_heading_error_;
    }
    if (cached_has_bits & 0x00001000u) {
      enable_lat_error_ = from.enable_lat_error_;
    }
    if (cached_has_bits & 0x00002000u) {
      lookahead_station_ = from.lookahead_station_;
    }
    if (cached_has_bits & 0x00004000u) {
      lookback_station_ = from.lookback_station_;
    }
    if (cached_has_bits & 0x00008000u) {
      cutoff_freq_ = from.cutoff_freq_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00ff0000u) {
    if (cached_has_bits & 0x00010000u) {
      heading_error_gain_ = from.heading_error_gain_;
    }
    if (cached_has_bits & 0x00020000u) {
      lat_error_gain_ = from.lat_error_gain_;
    }
    if (cached_has_bits & 0x00040000u) {
      lat_error_threshold_ = from.lat_error_threshold_;
    }
    if (cached_has_bits & 0x00080000u) {
      heading_error_threshold_ = from.heading_error_threshold_;
    }
    if (cached_has_bits & 0x00100000u) {
      purepursuit_minimum_lookahead_distance_ = from.purepursuit_minimum_lookahead_distance_;
    }
    if (cached_has_bits & 0x00200000u) {
      purepursuit_maximum_lookahead_distance_ = from.purepursuit_maximum_lookahead_distance_;
    }
    if (cached_has_bits & 0x00400000u) {
      purepursuit_speed_to_lookahead_ratio_ = from.purepursuit_speed_to_lookahead_ratio_;
    }
    if (cached_has_bits & 0x00800000u) {
      lat_error_min_threshold_ = from.lat_error_min_threshold_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x01000000u) {
    _internal_set_heading_error_min_threshold(from._internal_heading_error_min_threshold());
  }
}

void PurePursuitControllerConf::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:legion.control.PurePursuitControllerConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PurePursuitControllerConf::CopyFrom(const PurePursuitControllerConf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:legion.control.PurePursuitControllerConf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PurePursuitControllerConf::IsInitialized() const {
  return true;
}

void PurePursuitControllerConf::InternalSwap(PurePursuitControllerConf* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PurePursuitControllerConf, heading_error_min_threshold_)
      + sizeof(PurePursuitControllerConf::heading_error_min_threshold_)
      - PROTOBUF_FIELD_OFFSET(PurePursuitControllerConf, heading_error_pid_conf_)>(
          reinterpret_cast<char*>(&heading_error_pid_conf_),
          reinterpret_cast<char*>(&other->heading_error_pid_conf_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PurePursuitControllerConf::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace control
}  // namespace legion
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::legion::control::PurePursuitControllerConf* Arena::CreateMaybeMessage< ::legion::control::PurePursuitControllerConf >(Arena* arena) {
  return Arena::CreateMessageInternal< ::legion::control::PurePursuitControllerConf >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
