// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/control/src/proto/scheduler.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto;
namespace legion {
namespace control {
class Scheduler;
class SchedulerDefaultTypeInternal;
extern SchedulerDefaultTypeInternal _Scheduler_default_instance_;
}  // namespace control
}  // namespace legion
PROTOBUF_NAMESPACE_OPEN
template<> ::legion::control::Scheduler* Arena::CreateMaybeMessage<::legion::control::Scheduler>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace legion {
namespace control {

// ===================================================================

class Scheduler PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:legion.control.Scheduler) */ {
 public:
  inline Scheduler() : Scheduler(nullptr) {}
  virtual ~Scheduler();

  Scheduler(const Scheduler& from);
  Scheduler(Scheduler&& from) noexcept
    : Scheduler() {
    *this = ::std::move(from);
  }

  inline Scheduler& operator=(const Scheduler& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scheduler& operator=(Scheduler&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Scheduler& default_instance();

  static inline const Scheduler* internal_default_instance() {
    return reinterpret_cast<const Scheduler*>(
               &_Scheduler_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Scheduler& a, Scheduler& b) {
    a.Swap(&b);
  }
  inline void Swap(Scheduler* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scheduler* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Scheduler* New() const final {
    return CreateMaybeMessage<Scheduler>(nullptr);
  }

  Scheduler* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Scheduler>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Scheduler& from);
  void MergeFrom(const Scheduler& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Scheduler* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "legion.control.Scheduler";
  }
  protected:
  explicit Scheduler(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto);
    return ::descriptor_table_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kRatioFieldNumber = 2,
    kErrorFieldNumber = 3,
  };
  // optional double speed = 1;
  bool has_speed() const;
  private:
  bool _internal_has_speed() const;
  public:
  void clear_speed();
  double speed() const;
  void set_speed(double value);
  private:
  double _internal_speed() const;
  void _internal_set_speed(double value);
  public:

  // optional double ratio = 2;
  bool has_ratio() const;
  private:
  bool _internal_has_ratio() const;
  public:
  void clear_ratio();
  double ratio() const;
  void set_ratio(double value);
  private:
  double _internal_ratio() const;
  void _internal_set_ratio(double value);
  public:

  // optional double error = 3;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  double error() const;
  void set_error(double value);
  private:
  double _internal_error() const;
  void _internal_set_error(double value);
  public:

  // @@protoc_insertion_point(class_scope:legion.control.Scheduler)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double speed_;
  double ratio_;
  double error_;
  friend struct ::TableStruct_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Scheduler

// optional double speed = 1;
inline bool Scheduler::_internal_has_speed() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Scheduler::has_speed() const {
  return _internal_has_speed();
}
inline void Scheduler::clear_speed() {
  speed_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double Scheduler::_internal_speed() const {
  return speed_;
}
inline double Scheduler::speed() const {
  // @@protoc_insertion_point(field_get:legion.control.Scheduler.speed)
  return _internal_speed();
}
inline void Scheduler::_internal_set_speed(double value) {
  _has_bits_[0] |= 0x00000001u;
  speed_ = value;
}
inline void Scheduler::set_speed(double value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:legion.control.Scheduler.speed)
}

// optional double ratio = 2;
inline bool Scheduler::_internal_has_ratio() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Scheduler::has_ratio() const {
  return _internal_has_ratio();
}
inline void Scheduler::clear_ratio() {
  ratio_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Scheduler::_internal_ratio() const {
  return ratio_;
}
inline double Scheduler::ratio() const {
  // @@protoc_insertion_point(field_get:legion.control.Scheduler.ratio)
  return _internal_ratio();
}
inline void Scheduler::_internal_set_ratio(double value) {
  _has_bits_[0] |= 0x00000002u;
  ratio_ = value;
}
inline void Scheduler::set_ratio(double value) {
  _internal_set_ratio(value);
  // @@protoc_insertion_point(field_set:legion.control.Scheduler.ratio)
}

// optional double error = 3;
inline bool Scheduler::_internal_has_error() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Scheduler::has_error() const {
  return _internal_has_error();
}
inline void Scheduler::clear_error() {
  error_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Scheduler::_internal_error() const {
  return error_;
}
inline double Scheduler::error() const {
  // @@protoc_insertion_point(field_get:legion.control.Scheduler.error)
  return _internal_error();
}
inline void Scheduler::_internal_set_error(double value) {
  _has_bits_[0] |= 0x00000004u;
  error_ = value;
}
inline void Scheduler::set_error(double value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:legion.control.Scheduler.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace control
}  // namespace legion

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2fcontrol_2fsrc_2fproto_2fscheduler_2eproto
